/* Supabase adapter. Never falls back to the unauthenticated preview server. */
'use strict';
const ceConfig=window.CE_CONFIG||{};
const configured=/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(ceConfig.supabaseUrl||'')&&/^sb_publishable_/.test(ceConfig.publishableKey||'');
const ce= configured?supabase.createClient(ceConfig.supabaseUrl,ceConfig.publishableKey,{auth:{flowType:'pkce',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
const nativeFetch=window.fetch.bind(window);
let authBusy=false,commandBusy=false,orderRequestId=null,authReady=false,connectionUnavailable=false,refreshTimer;
const originalRegister=renderRegister,originalRoute=renderRoute,originalShopDetails=renderShopDetails;
const originalStock=crmAvailable;
async function api(body){
 if(!ce)throw Error('Supabase is not connected yet.');
 const {data:{session}}=await ce.auth.getSession();
 const headers={'Content-Type':'application/json',apikey:ceConfig.publishableKey};if(session)headers.Authorization='Bearer '+session.access_token;
 const r=await nativeFetch(ceConfig.supabaseUrl+'/functions/v1/crm-api',{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});let d;try{d=await r.json();}catch{throw Error('The server could not complete this request.');}
 if(!r.ok){if(r.status===401){clearPrivateState();renderLogin();}const e=Error(d.error||'Unable to complete the request');e.status=r.status;throw e;}return d;
}
window.fetch=async function(input,options){
 const path=typeof input==='string'?input:'';
 // Public vehicle lookup uses its read-only Vercel endpoint, independently of account setup.
 if(path.startsWith('/api/workspace'))throw Error('The legacy workspace endpoint is disabled.');
 return nativeFetch(input,options);
};
function clearPrivateState(preserveCart=false){state.user=null;state.accounts=[];state.orders=[];state.crm={quotes:[],tasks:[],purchases:[],inventory:{},activities:[]};state.cart=[];state.discountCodes=[];state.lastOrderId=null;checkoutFulfillment=null;checkoutDiscountCode=null;adminOrderDraft=null;quickOrderLines=[];quoteDraft=[];PARTS.forEach(p=>{p.priceCents=0;p.pricePending=true;p.costCents=null;p.available=null;});sessionStorage.removeItem('ce-preview-user');if(!preserveCart)sessionStorage.removeItem('ce-preview-cart');workspaceReady=false;workspaceSaved='';workspaceConflict=false;renderHeader();}
function applyRemote(d){
 const previous=state.user?.id;state.user=d.user;
 for(const k of ['accounts','orders','storeSettings','discountCodes'])state[k]=d.data[k];state.crm=d.data.crm;restoreCatalogProducts(d.data.products);for(const p of d.data.products){const local=byNumber(p.partNumber);if(local)Object.assign(local,p);}
 if(previous&&previous!==state.user?.id)state.cart=[];
 connectionUnavailable=false;workspaceRevision=d.revision;workspaceSaved=JSON.stringify(workspaceData());workspaceReady=true;workspaceConflict=false;renderHeader();return true;
}
async function loadRemote(){const d=await api({action:'bootstrap'});return applyRemote(d);}
rememberPreviewUser=function(){try{sessionStorage.removeItem('ce-preview-user');sessionStorage.setItem('ce-preview-cart',JSON.stringify({owner:state.user?.id||null,lines:state.cart}));}catch{}};
crmAvailable=function(num){return state.user?.role==='ADMIN'?originalStock(num):(byNumber(num)?.available??null);};
renderLogin=function(){authForm(false);};renderAdminLogin=function(){authForm(true);};
function authForm(staff){
 if(state.user&&state.user.status!=='APPLICATION_REQUIRED'){nav(loggedInLandingHash());return;}
 app.innerHTML=`<div class="page-narrow" style="max-width:440px"><span class="eyebrow">${staff?'Converter Express team':'Your shop account'}</span><h1 style="font-size:34px;margin:16px 0">${staff?'Admin sign in':'Welcome back'}</h1><p class="muted">${staff?'Sign in to manage your business.':'Your orders, deliveries, and invoices in one place.'}</p><form id="authForm" onsubmit="authLogin(event)" style="margin-top:26px"><label class="field-label" for="authEmail">Email</label><input class="field" id="authEmail" name="email" type="email" autocomplete="username" required/><label class="field-label" for="authPassword" style="margin-top:18px">Password</label><input class="field" id="authPassword" name="password" type="password" autocomplete="current-password" required/><label style="display:block;margin-top:10px;font-size:13px"><input type="checkbox" onchange="document.getElementById('authPassword').type=this.checked?'text':'password'"/> Show password</label><p id="authStatus" role="status" style="margin:16px 0">${configured?'':'Sign-in is temporarily unavailable. Please try again later.'}</p><button class="btn btn-primary btn-block" ${!configured?'disabled':''}>Sign in</button></form><button class="btn btn-outline btn-block" style="margin-top:12px" onclick="resetPassword()" ${!configured?'disabled':''}>Forgot password?</button>${staff?'':'<p style="margin-top:24px">New here? <a class="link-accent" href="#/register">Open a shop account</a></p>'}</div>`;renderHeader();
}
async function authLogin(e){e.preventDefault();if(authBusy)return;authBusy=true;const button=e.target.querySelector('button');button.disabled=true;const status=document.getElementById('authStatus');status.textContent='Signing in…';try{const {error}=await ce.auth.signInWithPassword({email:e.target.email.value.trim(),password:e.target.password.value});if(error)throw Error('Unable to sign in. Check your email, password, and email confirmation.');if(await loadRemote()){nav(state.user?.status==='APPLICATION_REQUIRED'?'#/register':loggedInLandingHash());render();}}catch(err){status.textContent=err.message;}finally{authBusy=false;button.disabled=false;}}
async function resetPassword(){const email=document.getElementById('authEmail').value.trim();const status=document.getElementById('authStatus');if(!email){status.textContent='Enter your email above first.';return;}const {error}=await ce.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});status.textContent=error?'Password recovery is unavailable. Please contact the administrator.':'If your account can receive recovery email, a reset link has been requested.';}
function passwordForm(){app.innerHTML=`<div class="page-narrow"><h1>Set a new password</h1><form onsubmit="changePassword(event)" style="margin-top:24px"><label class="field-label">New password</label><input class="field" type="password" name="password" minlength="10" maxlength="128" autocomplete="new-password" required/><p class="muted">Use at least 10 characters.</p><p id="passwordStatus" role="status"></p><button class="btn btn-primary" style="margin-top:20px">Save password</button></form></div>`;}
async function changePassword(e){e.preventDefault();const {error}=await ce.auth.updateUser({password:e.target.password.value});if(error){document.getElementById('passwordStatus').textContent=error.message;return;}await ce.auth.signOut({scope:'global'});clearPrivateState();nav('#/login');renderLogin();document.getElementById('authStatus').textContent='Password changed. Sign in again.';}
signOut=async function(){if(ce){const {error}=await ce.auth.signOut({scope:'global'});if(error){workspaceStatus('Unable to end the server session. Check your connection and retry.',true);return;}}clearPrivateState();if(configured)await loadRemote();nav('#/');render();};
renderRegister=function(){const u=state.user;if(u?.status==='APPLICATION_REQUIRED')state.user=null;originalRegister();state.user=u;const f=document.getElementById('regForm');if(!f)return;f.password.minLength=10;f.password.maxLength=128;f.password.autocomplete='new-password';if(u?.status==='APPLICATION_REQUIRED'){f.email.value=u.email;f.email.readOnly=true;f.password.closest('.field-group').remove();app.querySelector('h1').textContent='Finish your shop application';app.querySelector('h1 + p').textContent='You’re signed in and your email is verified. Submit your shop details and business license below for review. Pricing and ordering unlock after approval.';f.parentElement.querySelector('a[href="#/login"]')?.closest('p').remove();}if(!configured){f.querySelector('button').disabled=true;f.insertAdjacentHTML('beforeend','<p role="status">Account setup is temporarily unavailable. Please try again later.</p>');}};
submitRegister=async function(e){e.preventDefault();const f=e.target;if(authBusy||!f.reportValidity())return;authBusy=true;const button=f.querySelector('button');button.disabled=true;let status=f.querySelector('[role=status]');if(!status){status=document.createElement('p');status.setAttribute('role','status');f.append(status);}try{
 if(!state.user){const {data,error}=await ce.auth.signUp({email:f.email.value.trim(),password:f.password.value,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;if(!data.session){status.innerHTML='If your email still needs verification, check your inbox and spam folder for a Converter Express link. Already verified? <a class="link-accent" href="#/login">Sign in to finish your shop application</a>. You can also reset your password on the sign-in page.';return;}await loadRemote();}
 const {data:{user}}=await ce.auth.getUser();if(!user)throw Error('Sign in before submitting your application.');const file=f.licenseFile.files[0];if(!file||file.size>2097152||!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))throw Error('Choose a JPG, PNG, WebP, or PDF up to 2 MB.');const path=user.id+'/'+crypto.randomUUID();const upload=await ce.storage.from('business-licenses').upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;
 const keys=['shopName','contactName','phone','addressLine1','city','state','postalCode'];const d=await api({action:'application',fields:Object.fromEntries(keys.map(k=>[k,f.elements[k].value.trim()])),licensePath:path});applyRemote(d);nav('#/account/pending');render();
 }catch(e){status.textContent=e.message;}finally{authBusy=false;button.disabled=false;}};
saveWorkspace=async function(){if(!workspaceReady||workspaceSaving||commandBusy||workspaceConflict||state.user?.role!=='ADMIN')return;const snapshot=JSON.stringify(workspaceData());if(snapshot===workspaceSaved)return;workspaceSaving=true;workspaceStatus('Saving changes…');try{const d=await api({action:'admin-save',revision:workspaceRevision,data:JSON.parse(snapshot)});workspaceRevision=d.revision;workspaceSaved=snapshot;workspaceStatus(d.emails?.some(m=>m.status!=='accepted')?'Order saved. Review its email status to retry the confirmation.':'Saved to your workspace');}catch(e){if(e.status===409)workspaceConflict=true;workspaceStatus(e.message,true);}finally{workspaceSaving=false;}};
async function shopCommand(body){if(commandBusy)throw Error('Please wait for the current change to finish.');commandBusy=true;try{const d=await api(body);applyRemote(d);workspaceStatus(body.action==='order'&&d.email?.status!=='accepted'?'Order saved. Confirmation email is pending; check Order emails.':'Saved to your workspace');return d.result;}finally{commandBusy=false;}}
toggleSavedPart=async function(num){try{const parts=shopSavedParts();await shopCommand({action:'saved-parts',parts:parts.includes(num)?parts.filter(n=>n!==num):[...parts,num]});renderRoute();}catch(e){workspaceStatus(e.message,true);}};
saveShopDetails=async function(form){if(!form.reportValidity())return;try{await shopCommand({action:'profile',fields:Object.fromEntries(new FormData(form))});renderShopDetails();document.getElementById('shopSaveStatus').textContent='Shop details saved.';}catch(e){document.getElementById('shopSaveStatus').textContent=e.message;}};
const originalSaveJob=saveOrderJob;
saveOrderJob=async function(id){if(state.user?.role==='ADMIN')return originalSaveJob(id);try{await shopCommand({action:'job',orderId:id,job:readJobFields('edit')});document.getElementById('jobStatus').textContent='Job reference saved.';}catch(e){document.getElementById('jobStatus').textContent=e.message;}};
submitServiceRequest=async function(id,form){if(!form.reportValidity())return;const status=form.querySelector('.request-status');try{const f=new FormData(form),files=[...form.elements.photos.files];if(files.length>3)throw Error('Choose up to 3 photos.');const photos=await Promise.all(files.map(requestPhotoData));await shopCommand({action:'request',orderId:id,request:{type:f.get('type'),partNumber:f.get('part'),message:f.get('message'),photos}});renderOrderDetail(id);}catch(e){status.textContent=e.message;}};
let quoteSequence=0;
function orderInputs(){return {items:state.cart.map(l=>({partId:l.partId,quantity:l.quantity})),fulfillment:checkoutFulfillment,job:readJobFields('checkout'),poNumber:document.getElementById('poNumber')?.value||'',notes:document.getElementById('notes')?.value||'',discountCode:checkoutDiscountCode||''};}
renderCheckoutTotals=async function(){const el=document.getElementById('totalsCard'),button=document.getElementById('payBtn');if(!el||!checkoutFulfillment)return;const seq=++quoteSequence;if(!checkoutDiscountCode&&firstOrderEligible())checkoutDiscountCode='WELCOME50';button.disabled=true;el.textContent='Confirming prices and availability…';try{const {quote:q}=await api({action:'quote',idempotencyKey:crypto.randomUUID(),...orderInputs()});if(seq!==quoteSequence)return;el.innerHTML=[['Subtotal',q.subtotalCents],['Discount',-q.discountCents],['Delivery',q.shippingCents],['Tax',q.taxCents],['Total',q.totalCents]].map(([label,value])=>`<div class="line-item ${label==='Total'?'total':''}"><span>${label}</span><span>${fmt(value)}</span></div>`).join('');button.textContent='Submit order · '+fmt(q.totalCents);button.disabled=false;}catch(e){if(seq===quoteSequence)el.textContent=e.message;}};
applyDiscountCode=function(){checkoutDiscountCode=document.getElementById('promoInput').value.trim()||(firstOrderEligible()?'WELCOME50':'');renderCheckoutTotals();};
fakePay=async function(){const button=document.getElementById('payBtn');if(button.disabled)return;button.disabled=true;try{orderRequestId ||=crypto.randomUUID();const o=await shopCommand({action:'order',idempotencyKey:orderRequestId,items:state.cart.map(l=>({partId:l.partId,quantity:l.quantity})),fulfillment:checkoutFulfillment,job:readJobFields('checkout'),poNumber:document.getElementById('poNumber')?.value||'',notes:document.getElementById('notes')?.value||'',discountCode:checkoutDiscountCode||''});state.lastOrderId=o.id;state.cart=[];orderRequestId=null;rememberPreviewUser();nav('#/checkout/success');render();}catch(e){workspaceStatus(e.message,true);}finally{button.disabled=false;}};
async function openLicense(id){try{const d=await api({action:'license',accountId:id});const a=document.createElement('a');a.href=d.url;a.target='_blank';a.rel='noopener noreferrer';a.click();}catch(e){workspaceStatus(e.message,true);}}
renderShopDetails=function(){originalShopDetails();if(state.user){const el=document.createElement('p');el.style.marginTop='24px';el.innerHTML='<a class="link-accent" href="#/account/password">Change password</a>';app.append(el);}};
function verificationForm(){
 const params=new URLSearchParams((location.hash.split('?')[1]||''));const token=params.get('token_hash'),type=params.get('type');
 history.replaceState(null,'',location.pathname+location.search+'#/verify');
 app.innerHTML=`<div class="page-narrow" style="max-width:480px"><span class="eyebrow">Converter Express</span><h1 style="margin:18px 0">${type==='recovery'?'Reset your password':'Verify your email'}</h1><p>${type==='recovery'?'Continue to choose a new password for your shop account.':'Confirm your email to finish your shop application.'}</p><p id="verifyStatus" role="status" style="margin:20px 0"></p><button id="verifyAccount" class="btn btn-primary btn-block">${type==='recovery'?'Continue':'Verify my email'}</button><p style="margin-top:24px"><a href="#/login">Back to sign in</a></p></div>`;
 const button=document.getElementById('verifyAccount'),status=document.getElementById('verifyStatus');
 if(!configured||!token||!['email','recovery','invite','email_change'].includes(type)){button.disabled=true;status.textContent='Open the verification link from your latest email to continue.';return;}
 button.onclick=async()=>{button.disabled=true;status.textContent='Verifying…';try{const {error}=await ce.auth.verifyOtp({token_hash:token,type});if(error)throw error;await loadRemote();if(!state.user){status.textContent=type==='email_change'?'Email confirmed. Check your other inbox if another confirmation is required, then sign in.':'Email confirmed. Sign in to continue.';button.hidden=true;return;}nav(['recovery','invite'].includes(type)?'#/account/password':state.user?.status==='APPLICATION_REQUIRED'?'#/register':loggedInLandingHash());render();}catch(e){status.textContent='This link could not be verified. It may have expired or already been used. Try signing in, or request a new password-reset email.';button.disabled=false;}};
}
function publicRoute(){return /^#\/(?:$|(?:catalog|find-your-part|about|contact|returns|terms|privacy|login|register|verify)(?:[/?]|$))/.test(location.hash||'#/');}
function connectionErrorPage(){app.innerHTML='<div class="page-narrow"><h1>Account service unavailable</h1><p id="connectionError" role="status">We could not connect. Please try again to access your account.</p><button class="btn btn-primary" onclick="location.reload()">Try again</button> <a href="#/">Back to homepage</a></div>';}
renderRoute=function(){if(location.hash.split('?')[0]==='#/verify')return verificationForm();if(connectionUnavailable&&!publicRoute())return connectionErrorPage();if(location.hash==='#/account/password')return passwordForm();return originalRoute();};
async function startSupabase(){
 clearPrivateState(true);if(publicRoute()&&!location.hash.startsWith('#/verify'))render(true);if(!configured){render();workspaceStatus('Supabase is not connected yet. Account access is disabled.',true);return;}
 try{const savedCart=JSON.parse(sessionStorage.getItem('ce-preview-cart')||'null');ce.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')setTimeout(()=>{location.hash='#/account/password';passwordForm();},0);if(event==='SIGNED_OUT'){clearPrivateState();nav('#/login');renderLogin();}});await ce.auth.getSession();if(await loadRemote()){const saved=savedCart;if(saved&&saved.owner===state.user?.id&&Array.isArray(saved.lines))state.cart=saved.lines.filter(l=>byNumber(l.partId)&&Number.isSafeInteger(l.quantity)&&l.quantity>0);render(true);}authReady=true;setInterval(saveWorkspace,1200);setInterval(rememberPreviewUser,1200);refreshTimer=setInterval(async()=>{if(!workspaceSaving&&!commandBusy&&state.user?.role==='CUSTOMER'&&location.hash==='#/orders'&&!document.activeElement?.matches('input,textarea,select'))try{if(await loadRemote())renderRoute();}catch{}},15000);
 }catch(e){clearPrivateState();connectionUnavailable=true;render(true);}
}
startSupabase();

// The server renders previews from saved order data; the browser cannot choose a recipient.
renderEmailPreview=async function(id){
 if(!state.user){nav('#/login');return;}
 const o=findOrder(id);if(!canViewOrder(o)){app.innerHTML='<div class="page">Order not found.</div>';return;}
 app.innerHTML=`<div class="page-mid"><a id="mailBack">← Back to order</a><h1 style="font-size:28px;margin:20px 0">Order emails</h1><p class="muted">Preview the email before sending. Accepted means Resend accepted it—not that it reached the inbox.</p><div style="display:flex;gap:12px;flex-wrap:wrap;margin:24px 0"><label>Message <select class="field" id="orderMailKind"><option value="confirmation">Order confirmation</option><option value="invoice">Invoice</option></select></label>${state.user.role==='ADMIN'?'<button class="btn btn-primary" id="sendOrderMail" disabled>Send email</button>':''}</div><p id="orderMailStatus" role="status"></p><iframe title="Customer email preview" id="orderMailFrame" sandbox="" style="width:100%;height:780px;border:1px solid #dfe3df;border-radius:8px;background:#efefeb;margin-top:20px"></iframe></div>`;
 document.getElementById('mailBack').href='#/orders/'+encodeURIComponent(id);
 const select=document.getElementById('orderMailKind'),status=document.getElementById('orderMailStatus'),button=document.getElementById('sendOrderMail'),frame=document.getElementById('orderMailFrame');let sequence=0;
 const load=async()=>{const seq=++sequence;if(button)button.disabled=true;status.textContent='Loading saved order…';try{const kind=select.value;const [preview,delivery]=await Promise.all([api({action:'order-email',orderId:id,kind,operation:'preview'}),api({action:'order-email',orderId:id,kind,operation:'status'})]);if(seq!==sequence)return;frame.srcdoc=preview.html;const sent=delivery.emails.find(e=>e.kind===kind);status.textContent='To: '+preview.to+' · '+(sent?sent.status==='accepted'?'Accepted by Resend.':sent.status+(sent.issue?' — '+sent.issue:''):'Not sent.');if(!delivery.configured)status.textContent+=' Email setup is incomplete.';if(button){button.disabled=!delivery.configured||sent?.status==='accepted'||o.cancelled;button.textContent=sent&&sent.status!=='accepted'?'Retry email':'Send email';}}catch(e){status.textContent=e.message;}};
 select.onchange=load;if(button)button.onclick=async()=>{button.disabled=true;select.disabled=true;status.textContent='Sending…';try{const r=await api({action:'order-email',orderId:id,kind:select.value,operation:'send'});await load();if(r.email.issue)status.textContent+=' '+r.email.issue;}catch(e){status.textContent=e.message;button.disabled=false;}finally{select.disabled=false;}};await load();
};

deleteCatalogPart=async function(num){
 if(!requireAdmin())return;const status=document.getElementById('productDeleteStatus'),button=status?.parentElement.querySelector('button');if(!status||!byNumber(num))return;
 if(workspaceSaving||commandBusy){status.textContent='Please wait for the current change to finish, then try again.';return;}
 if(!confirm('Delete part '+num+'? This removes it from your catalog and inventory.'))return;
 button.disabled=true;status.textContent='Deleting part…';
 try{
  await saveWorkspace();if(workspaceConflict||JSON.stringify(workspaceData())!==workspaceSaved)throw Error('Save your pending changes before deleting this part. Reload if another administrator saved changes.');
  await shopCommand({action:'delete-product',partNumber:num});state.cart=state.cart.filter(l=>l.partId!==num);nav('#/admin/products');renderAdminProducts();
 }catch(e){status.textContent=e.message;}finally{button.disabled=false;}
};


deleteManualRecord=async function(kind,id,partNumber,button){
 if(!requireAdmin())return;const status=button.parentElement.querySelector('.manual-delete-status');
 if(workspaceSaving||commandBusy){status.textContent='Please wait for the current change to finish, then try again.';return;}
 const count=kind==='series'?PARTS.filter(p=>p.category===id).length:0;
 if(!confirm(button.textContent+'?'+(kind==='series'?' This removes '+id+' and its '+count+' unused parts.':' This permanently removes the saved entry.')))return;
 button.disabled=true;status.textContent='Deleting…';
 try{await saveWorkspace();if(workspaceConflict||JSON.stringify(workspaceData())!==workspaceSaved)throw Error('Save pending changes before deleting. Reload if another administrator saved changes.');
 await shopCommand({action:'delete-record',kind,id,...(kind==='price'?{partNumber}:{})});state.cart=state.cart.filter(l=>byNumber(l.partId));
 if(kind==='order'&&location.hash.includes('/orders/'+id))nav('#/admin/orders');renderRoute();
 }catch(e){status.textContent=e.message;}finally{button.disabled=false;}
};
