/* Supabase adapter. Never falls back to the unauthenticated preview server. */
'use strict';
const ceConfig=window.CE_CONFIG||{};
const configured=/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(ceConfig.supabaseUrl||'')&&/^sb_publishable_/.test(ceConfig.publishableKey||'');
const ce= configured?supabase.createClient(ceConfig.supabaseUrl,ceConfig.publishableKey,{auth:{flowType:'pkce',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
const nativeFetch=window.fetch.bind(window);
let authBusy=false,commandBusy=false,orderRequestId=null,authReady=false,connectionUnavailable=false,refreshTimer;
const originalRegister=renderRegister,originalRoute=renderRoute,originalShopDetails=renderShopDetails,originalBillingEditor=billingEditorHtml;
const originalStock=crmAvailable;
async function api(body){
 if(!ce)throw Error('Supabase is not connected yet.');
 const {data:{session}}=await ce.auth.getSession();
 const headers={'Content-Type':'application/json',apikey:ceConfig.publishableKey};if(session)headers.Authorization='Bearer '+session.access_token;
 const r=await nativeFetch(ceConfig.supabaseUrl+'/functions/v1/crm-api',{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});let d;try{d=await r.json();}catch{throw Error('The server could not complete this request.');}
 if(!r.ok){if(r.status===401){clearPrivateState();renderLogin();}const e=Error(d.error||'Unable to complete the request');e.status=r.status;throw e;}return d;
}
window.fetch=async function(input,options){
 const path=typeof input==='string'?input:'';
 // Public vehicle lookup uses its read-only Vercel endpoint, independently of account setup.
 if(path.startsWith('/api/workspace'))throw Error('The legacy workspace endpoint is disabled.');
 return nativeFetch(input,options);
};
function clearPrivateState(preserveCart=false){state.user=null;state.accounts=[];state.orders=[];state.crm={quotes:[],tasks:[],purchases:[],inventory:{},activities:[]};state.cart=[];state.discountCodes=[];state.lastOrderId=null;checkoutFulfillment=null;checkoutDiscountCode=null;adminOrderDraft=null;quickOrderLines=[];quoteDraft=[];PARTS.forEach(p=>{p.priceCents=0;p.pricePending=true;p.costCents=null;p.available=null;});sessionStorage.removeItem('ce-preview-user');if(!preserveCart)sessionStorage.removeItem('ce-preview-cart');workspaceReady=false;workspaceSaved='';workspaceConflict=false;renderHeader();}
function applyRemote(d){if(typeof d.paymentConfigured==='boolean')window.ceWhopReady=d.paymentConfigured;
 const previous=state.user?.id;state.user=d.user;
 for(const k of ['accounts','orders','storeSettings','discountCodes'])state[k]=d.data[k];state.crm=d.data.crm;restoreCatalogProducts(d.data.products);for(const p of d.data.products){const local=byNumber(p.partNumber);if(local)Object.assign(local,p);}
 if(previous&&previous!==state.user?.id)state.cart=[];
 connectionUnavailable=false;workspaceRevision=d.revision;workspaceSaved=JSON.stringify(workspaceData());workspaceReady=true;workspaceConflict=false;renderHeader();return true;
}
async function loadRemote(){const d=await api({action:'bootstrap'});return applyRemote(d);}
rememberPreviewUser=function(){try{sessionStorage.removeItem('ce-preview-user');sessionStorage.setItem('ce-preview-cart',JSON.stringify({owner:state.user?.id||null,lines:state.cart}));}catch{}};
crmAvailable=function(num){return state.user?.role==='ADMIN'?originalStock(num):(byNumber(num)?.available??null);};
renderLogin=function(){authForm(false);};renderAdminLogin=function(){authForm(true);};
function authForm(staff){
 if(state.user&&state.user.status!=='APPLICATION_REQUIRED'){nav(loggedInLandingHash());return;}
 app.innerHTML=`<div class="page-narrow" style="max-width:440px"><span class="eyebrow">${staff?'Converter Express team':'Your shop account'}</span><h1 style="font-size:34px;margin:16px 0">${staff?'Admin sign in':'Welcome back'}</h1><p class="muted">${staff?'Sign in to manage your business.':'Your orders, deliveries, and invoices in one place.'}</p><form id="authForm" onsubmit="authLogin(event)" style="margin-top:26px"><label class="field-label" for="authEmail">Email</label><input class="field" id="authEmail" name="email" type="email" autocomplete="username" required/><label class="field-label" for="authPassword" style="margin-top:18px">Password</label><input class="field" id="authPassword" name="password" type="password" autocomplete="current-password" required/><label style="display:block;margin-top:10px;font-size:13px"><input type="checkbox" onchange="document.getElementById('authPassword').type=this.checked?'text':'password'"/> Show password</label><p id="authStatus" role="status" style="margin:16px 0">${configured?'':'Sign-in is temporarily unavailable. Please try again later.'}</p><button class="btn btn-primary btn-block" ${!configured?'disabled':''}>Sign in</button></form><button class="btn btn-outline btn-block" style="margin-top:12px" onclick="resetPassword()" ${!configured?'disabled':''}>Forgot password?</button>${staff?'':'<p style="margin-top:24px">New here? <a class="link-accent" href="#/register">Open a shop account</a></p>'}</div>`;renderHeader();
}
async function authLogin(e){e.preventDefault();if(authBusy)return;authBusy=true;const button=e.target.querySelector('button');button.disabled=true;const status=document.getElementById('authStatus');status.textContent='Signing in…';try{const {error}=await ce.auth.signInWithPassword({email:e.target.email.value.trim(),password:e.target.password.value});if(error)throw Error('Unable to sign in. Check your email, password, and email confirmation.');if(await loadRemote()){nav(state.user?.status==='APPLICATION_REQUIRED'?'#/register':loggedInLandingHash());render();}}catch(err){status.textContent=err.message;}finally{authBusy=false;button.disabled=false;}}
async function resetPassword(){const email=document.getElementById('authEmail').value.trim();const status=document.getElementById('authStatus');if(!email){status.textContent='Enter your email above first.';return;}const {error}=await ce.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});status.textContent=error?'Password recovery is unavailable. Please contact the administrator.':'If your account can receive recovery email, a reset link has been requested.';}
function passwordForm(){app.innerHTML=`<div class="page-narrow"><h1>Set a new password</h1><form onsubmit="changePassword(event)" style="margin-top:24px"><label class="field-label">New password</label><input class="field" type="password" name="password" minlength="10" maxlength="128" autocomplete="new-password" required/><p class="muted">Use at least 10 characters.</p><p id="passwordStatus" role="status"></p><button class="btn btn-primary" style="margin-top:20px">Save password</button></form></div>`;}
async function changePassword(e){e.preventDefault();const {error}=await ce.auth.updateUser({password:e.target.password.value});if(error){document.getElementById('passwordStatus').textContent=error.message;return;}await ce.auth.signOut({scope:'global'});clearPrivateState();nav('#/login');renderLogin();document.getElementById('authStatus').textContent='Password changed. Sign in again.';}
signOut=async function(){if(ce){const {error}=await ce.auth.signOut({scope:'global'});if(error){workspaceStatus('Unable to end the server session. Check your connection and retry.',true);return;}}clearPrivateState();if(configured)await loadRemote();nav('#/');render();};
renderRegister=function(){const u=state.user;if(u?.status==='APPLICATION_REQUIRED')state.user=null;originalRegister();state.user=u;const f=document.getElementById('regForm');if(!f)return;f.password.minLength=10;f.password.maxLength=128;f.password.autocomplete='new-password';if(u?.status==='APPLICATION_REQUIRED'){f.email.value=u.email;f.email.readOnly=true;f.password.closest('.field-group').remove();app.querySelector('h1').textContent='Finish your shop application';app.querySelector('h1 + p').textContent='You’re signed in and your email is verified. Submit your shop details and business license below for review. Pricing and ordering unlock after approval.';f.parentElement.querySelector('a[href="#/login"]')?.closest('p').remove();}if(!configured){f.querySelector('button').disabled=true;f.insertAdjacentHTML('beforeend','<p role="status">Account setup is temporarily unavailable. Please try again later.</p>');}};
submitRegister=async function(e){e.preventDefault();const f=e.target;if(authBusy||!f.reportValidity())return;authBusy=true;const button=f.querySelector('button');button.disabled=true;let status=f.querySelector('[role=status]');if(!status){status=document.createElement('p');status.setAttribute('role','status');f.append(status);}try{
 if(!state.user){const {data,error}=await ce.auth.signUp({email:f.email.value.trim(),password:f.password.value,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;if(!data.session){status.innerHTML='If your email still needs verification, check your inbox and spam folder for a Converter Express link. Already verified? <a class="link-accent" href="#/login">Sign in to finish your shop application</a>. You can also reset your password on the sign-in page.';return;}await loadRemote();}
 const {data:{user}}=await ce.auth.getUser();if(!user)throw Error('Sign in before submitting your application.');const file=f.licenseFile.files[0];if(!file||file.size>2097152||!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))throw Error('Choose a JPG, PNG, WebP, or PDF up to 2 MB.');const path=user.id+'/'+crypto.randomUUID();const upload=await ce.storage.from('business-licenses').upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;
 const keys=['shopName','contactName','phone','addressLine1','city','state','postalCode'];const d=await api({action:'application',fields:Object.fromEntries(keys.map(k=>[k,f.elements[k].value.trim()])),licensePath:path});applyRemote(d);nav('#/account/pending');render();
 }catch(e){status.textContent=e.message;}finally{authBusy=false;button.disabled=false;}};
saveWorkspace=async function(){if(!workspaceReady||workspaceSaving||commandBusy||workspaceConflict||state.user?.role!=='ADMIN')return;const snapshot=JSON.stringify(workspaceData());if(snapshot===workspaceSaved)return;workspaceSaving=true;workspaceStatus('Saving changes…');try{const d=await api({action:'admin-save',revision:workspaceRevision,data:JSON.parse(snapshot)});workspaceRevision=d.revision;workspaceSaved=snapshot;workspaceStatus(d.emails?.some(m=>m.status!=='accepted')?'Order saved. Review its email status to retry the confirmation.':'Saved to your workspace');}catch(e){if(e.status===409)workspaceConflict=true;workspaceStatus(e.message,true);}finally{workspaceSaving=false;}};
async function shopCommand(body){if(commandBusy)throw Error('Please wait for the current change to finish.');commandBusy=true;try{const d=await api(body);applyRemote(d);workspaceStatus(body.action==='order'&&d.email?.status!=='accepted'?'Order saved. Confirmation email is pending; check Order emails.':'Saved to your workspace');return d.result;}finally{commandBusy=false;}}
toggleSavedPart=async function(num){try{const parts=shopSavedParts();await shopCommand({action:'saved-parts',parts:parts.includes(num)?parts.filter(n=>n!==num):[...parts,num]});renderRoute();}catch(e){workspaceStatus(e.message,true);}};
saveShopDetails=async function(form){if(!form.reportValidity())return;try{await shopCommand({action:'profile',fields:Object.fromEntries(new FormData(form))});renderShopDetails();document.getElementById('shopSaveStatus').textContent='Shop details saved.';}catch(e){document.getElementById('shopSaveStatus').textContent=e.message;}};
const originalSaveJob=saveOrderJob;
saveOrderJob=async function(id){if(state.user?.role==='ADMIN')return originalSaveJob(id);try{await shopCommand({action:'job',orderId:id,job:readJobFields('edit')});document.getElementById('jobStatus').textContent='Job reference saved.';}catch(e){document.getElementById('jobStatus').textContent=e.message;}};
submitServiceRequest=async function(id,form){if(!form.reportValidity())return;const status=form.querySelector('.request-status');try{const f=new FormData(form),files=[...form.elements.photos.files];if(files.length>3)throw Error('Choose up to 3 photos.');const photos=await Promise.all(files.map(requestPhotoData));await shopCommand({action:'request',orderId:id,request:{type:f.get('type'),partNumber:f.get('part'),message:f.get('message'),photos}});renderOrderDetail(id);}catch(e){status.textContent=e.message;}};
let quoteSequence=0;
function orderInputs(){return {items:state.cart.map(l=>({partId:l.partId,quantity:l.quantity})),fulfillment:checkoutFulfillment,job:readJobFields('checkout'),poNumber:document.getElementById('poNumber')?.value||'',notes:document.getElementById('notes')?.value||'',discountCode:checkoutDiscountCode||''};}
renderCheckoutTotals=async function(){const el=document.getElementById('totalsCard'),button=document.getElementById('payBtn');if(!el||!checkoutFulfillment)return;const seq=++quoteSequence;if(!checkoutDiscountCode&&firstOrderEligible())checkoutDiscountCode='WELCOME50';button.disabled=true;el.textContent='Confirming prices and availability…';try{const {quote:q}=await api({action:'quote',idempotencyKey:crypto.randomUUID(),...orderInputs()});if(seq!==quoteSequence)return;el.innerHTML=[['Subtotal',q.subtotalCents],['Discount',-q.discountCents],['Delivery',q.shippingCents],['Tax',q.taxCents],['Total',q.totalCents]].map(([label,value])=>`<div class="line-item ${label==='Total'?'total':''}"><span>${label}</span><span>${fmt(value)}</span></div>`).join('');button.textContent='Continue to secure payment · '+fmt(q.totalCents);button.disabled=false;if(savedCheckout())queueMicrotask(fakePay);}catch(e){if(seq===quoteSequence)el.textContent=e.message;}};
applyDiscountCode=function(){checkoutDiscountCode=document.getElementById('promoInput').value.trim()||(firstOrderEligible()?'WELCOME50':'');renderCheckoutTotals();};
function savedCheckout(){try{return JSON.parse(sessionStorage.getItem('ce-checkout-reservation')||'null');}catch{return null;}}
function rememberCheckout(value){if(value)sessionStorage.setItem('ce-checkout-reservation',JSON.stringify(value));else sessionStorage.removeItem('ce-checkout-reservation');}
function checkoutMessage(status){return {READY:'Payment required',PROCESSING:'Payment processing',PAID:'Order confirmed',EXPIRED:'Checkout expired',FAILED:'Payment failed',REVIEW:'Payment review required'}[status]||'Checkout status unavailable';}
async function refreshCheckout(reservationId){const result=await api({action:'checkout-status',reservationId}),r=result.reservation;if(r.status==='PAID'&&r.orderId){rememberCheckout(null);orderRequestId=null;state.lastOrderId=r.orderId;state.cart=[];rememberPreviewUser();await loadRemote();nav('#/checkout/success');render();return r;}if(['PROCESSING','REVIEW'].includes(r.status)){const status=document.getElementById('checkoutPaymentStatus');if(status)status.textContent=r.status==='REVIEW'?'Payment needs review. Do not pay again. Contact Converter Express.':'Payment is processing. Do not submit another payment.';}return r;}
async function pollCheckout(reservationId){for(let i=0;i<8;i++){await new Promise(resolve=>setTimeout(resolve,1500));const r=await refreshCheckout(reservationId);if(['PAID','FAILED','EXPIRED','REVIEW'].includes(r.status))return r;}return null;}
async function mountCheckoutPayment(reservation){const totals=document.getElementById('totalsCard'),button=document.getElementById('payBtn');totals.insertAdjacentHTML('afterend',`<section id="checkoutPayment" class="card whop-invoice-payment" style="padding:22px;margin-top:16px"><span class="eyebrow">Secure payment</span><h2>${esc(checkoutMessage(reservation.status))}</h2><div class="whop-payment-frame"><div id="checkout-payment-element"></div><div id="checkout-branding-element"></div></div><button id="confirmCheckoutPayment" class="btn btn-primary btn-block" disabled>Loading secure payment…</button><p id="checkoutPaymentStatus" role="status">Connecting to Whop…</p></section>`);button.hidden=true;const status=document.getElementById('checkoutPaymentStatus'),pay=document.getElementById('confirmCheckoutPayment');if(['PROCESSING','REVIEW'].includes(reservation.status)){status.textContent=reservation.status==='REVIEW'?'Payment needs review. Do not pay again. Contact Converter Express.':'Payment is processing. Do not submit another payment.';await pollCheckout(reservation.id);return;}try{await loadWhopElements();const session=await api({action:'checkout-session',reservationId:reservation.id});if(session.status){status.textContent=checkoutMessage(session.status);return;}if(!validWhopSession(session))throw Error('Secure payment configuration is invalid.');const elements=window.WhopElements(),payments=elements.payments.create({accountId:session.accountId,currency:session.currency,amount:session.amount,returnUrl:location.origin+location.pathname+'#/checkout'});payments.create('payment',{onChange:event=>{pay.disabled=!event.complete;pay.textContent='Pay '+fmt(session.amount);status.textContent=event.complete?'Payment details are ready.':'Complete your payment details.';},onError:event=>{status.textContent=event?.message||'Check your payment details.';}}).mount('#checkout-payment-element');payments.create('branding').mount('#checkout-branding-element');pay.onclick=async()=>{pay.disabled=true;status.textContent='Securing payment…';try{const token=await payments.createConfirmationToken({billingDetails:session.billingDetails});if(!/^ctok_[A-Za-z0-9]+$/.test(token?.confirmationToken||''))throw Error('Payment details could not be secured.');const confirmed=await api({action:'checkout-confirm',reservationId:reservation.id,reference:session.reference,confirmationToken:token.confirmationToken});const outcome=await elements.payments.handleNextAction({clientSecret:confirmed.clientSecret,returnUrl:location.origin+location.pathname+'#/checkout'});if(outcome.lastPaymentError)throw Error(outcome.lastPaymentError.message||'Payment could not be completed.');status.textContent='Payment submitted. Waiting for verified confirmation…';await pollCheckout(reservation.id);}catch(e){status.textContent=e.message||'Payment could not be completed.';pay.disabled=false;}};}catch(e){status.textContent=e.message;}}
fakePay=async function(){const button=document.getElementById('payBtn');if(button.disabled)return;button.disabled=true;try{let existing=savedCheckout(),reservation;if(existing){reservation=(await api({action:'checkout-status',reservationId:existing.id})).reservation;if(['FAILED','EXPIRED'].includes(reservation.status)){rememberCheckout(null);existing=null;}}if(!existing){orderRequestId ||=crypto.randomUUID();reservation=(await api({action:'checkout-reserve',idempotencyKey:orderRequestId,...orderInputs()})).reservation;rememberCheckout({id:reservation.id,idempotencyKey:orderRequestId});}await mountCheckoutPayment(reservation);}catch(e){workspaceStatus(e.message,true);button.disabled=false;}};
async function openLicense(id){try{const d=await api({action:'license',accountId:id});const a=document.createElement('a');a.href=d.url;a.target='_blank';a.rel='noopener noreferrer';a.click();}catch(e){workspaceStatus(e.message,true);}}
renderShopDetails=function(){originalShopDetails();if(state.user){const el=document.createElement('p');el.style.marginTop='24px';el.innerHTML='<a class="link-accent" href="#/account/password">Change password</a>';app.append(el);}};
function verificationForm(){
 const params=new URLSearchParams((location.hash.split('?')[1]||''));const token=params.get('token_hash'),type=params.get('type');
 history.replaceState(null,'',location.pathname+location.search+'#/verify');
 app.innerHTML=`<div class="page-narrow" style="max-width:480px"><span class="eyebrow">Converter Express</span><h1 style="margin:18px 0">${type==='recovery'?'Reset your password':'Verify your email'}</h1><p>${type==='recovery'?'Continue to choose a new password for your shop account.':'Confirm your email to finish your shop application.'}</p><p id="verifyStatus" role="status" style="margin:20px 0"></p><button id="verifyAccount" class="btn btn-primary btn-block">${type==='recovery'?'Continue':'Verify my email'}</button><p style="margin-top:24px"><a href="#/login">Back to sign in</a></p></div>`;
 const button=document.getElementById('verifyAccount'),status=document.getElementById('verifyStatus');
 if(!configured||!token||!['email','recovery','invite','email_change'].includes(type)){button.disabled=true;status.textContent='Open the verification link from your latest email to continue.';return;}
 button.onclick=async()=>{button.disabled=true;status.textContent='Verifying…';try{const {error}=await ce.auth.verifyOtp({token_hash:token,type});if(error)throw error;await loadRemote();if(!state.user){status.textContent=type==='email_change'?'Email confirmed. Check your other inbox if another confirmation is required, then sign in.':'Email confirmed. Sign in to continue.';button.hidden=true;return;}nav(['recovery','invite'].includes(type)?'#/account/password':state.user?.status==='APPLICATION_REQUIRED'?'#/register':loggedInLandingHash());render();}catch(e){status.textContent='This link could not be verified. It may have expired or already been used. Try signing in, or request a new password-reset email.';button.disabled=false;}};
}
function publicRoute(){return /^#\/(?:$|(?:catalog|find-your-part|about|contact|returns|terms|privacy|login|register|verify)(?:[/?]|$))/.test(location.hash||'#/');}
function connectionErrorPage(){app.innerHTML='<div class="page-narrow"><h1>Account service unavailable</h1><p id="connectionError" role="status">We could not connect. Please try again to access your account.</p><button class="btn btn-primary" onclick="location.reload()">Try again</button> <a href="#/">Back to homepage</a></div>';}
renderRoute=function(){if(location.hash.split('?')[0]==='#/verify')return verificationForm();if(connectionUnavailable&&!publicRoute())return connectionErrorPage();if(location.hash==='#/account/password')return passwordForm();return originalRoute();};
async function startSupabase(){
 clearPrivateState(true);if(publicRoute()&&!location.hash.startsWith('#/verify'))render(true);if(!configured){render();workspaceStatus('Supabase is not connected yet. Account access is disabled.',true);return;}
 try{const savedCart=JSON.parse(sessionStorage.getItem('ce-preview-cart')||'null');ce.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')setTimeout(()=>{location.hash='#/account/password';passwordForm();},0);if(event==='SIGNED_OUT'){clearPrivateState();nav('#/login');renderLogin();}});await ce.auth.getSession();if(await loadRemote()){const saved=savedCart;if(saved&&saved.owner===state.user?.id&&Array.isArray(saved.lines))state.cart=saved.lines.filter(l=>byNumber(l.partId)&&Number.isSafeInteger(l.quantity)&&l.quantity>0);render(true);}authReady=true;setInterval(saveWorkspace,1200);setInterval(rememberPreviewUser,1200);refreshTimer=setInterval(async()=>{if(!workspaceSaving&&!commandBusy&&state.user?.role==='CUSTOMER'&&location.hash==='#/orders'&&!document.activeElement?.matches('input,textarea,select'))try{if(await loadRemote())renderRoute();}catch{}},15000);
 }catch(e){clearPrivateState();connectionUnavailable=true;render(true);}
}
startSupabase();

// The server renders previews from saved order data; the browser cannot choose a recipient.
renderEmailPreview=async function(id){
 if(!state.user){nav('#/login');return;}
 const o=findOrder(id);if(!canViewOrder(o)){app.innerHTML='<div class="page">Order not found.</div>';return;}
 app.innerHTML=`<div class="page-mid"><a id="mailBack">← Back to order</a><h1 style="font-size:28px;margin:20px 0">Order emails</h1><p class="muted">Preview the email before sending. Accepted means Resend accepted it—not that it reached the inbox.</p><div style="display:flex;gap:12px;flex-wrap:wrap;margin:24px 0"><label>Message <select class="field" id="orderMailKind"><option value="confirmation">Order confirmation</option><option value="invoice">Invoice</option></select></label>${state.user.role==='ADMIN'?'<button class="btn btn-primary" id="sendOrderMail" disabled>Send email</button>':''}</div><p id="orderMailStatus" role="status"></p><iframe title="Customer email preview" id="orderMailFrame" sandbox="" style="width:100%;height:780px;border:1px solid #dfe3df;border-radius:8px;background:#efefeb;margin-top:20px"></iframe></div>`;
 document.getElementById('mailBack').href='#/orders/'+encodeURIComponent(id);
 const select=document.getElementById('orderMailKind'),status=document.getElementById('orderMailStatus'),button=document.getElementById('sendOrderMail'),frame=document.getElementById('orderMailFrame');let sequence=0;
 const load=async()=>{const seq=++sequence;if(button)button.disabled=true;status.textContent='Loading saved order…';try{const kind=select.value;const [preview,delivery]=await Promise.all([api({action:'order-email',orderId:id,kind,operation:'preview'}),api({action:'order-email',orderId:id,kind,operation:'status'})]);if(seq!==sequence)return;frame.srcdoc=preview.html;const sent=delivery.emails.find(e=>e.kind===kind);status.textContent='To: '+preview.to+' · '+(sent?sent.status==='accepted'?'Accepted by Resend.':sent.status+(sent.issue?' — '+sent.issue:''):'Not sent.');if(!delivery.configured)status.textContent+=' Email setup is incomplete.';if(button){button.disabled=!delivery.configured||sent?.status==='accepted'||o.cancelled;button.textContent=sent&&sent.status!=='accepted'?'Retry email':'Send email';}}catch(e){status.textContent=e.message;}};
 select.onchange=load;if(button)button.onclick=async()=>{button.disabled=true;select.disabled=true;status.textContent='Sending…';try{const r=await api({action:'order-email',orderId:id,kind:select.value,operation:'send'});await load();if(r.email.issue)status.textContent+=' '+r.email.issue;}catch(e){status.textContent=e.message;button.disabled=false;}finally{select.disabled=false;}};await load();
};

deleteCatalogPart=async function(num){
 if(!requireAdmin())return;const status=document.getElementById('productDeleteStatus'),button=status?.parentElement.querySelector('button');if(!status||!byNumber(num))return;
 if(workspaceSaving||commandBusy){status.textContent='Please wait for the current change to finish, then try again.';return;}
 if(!confirm('Delete part '+num+'? This removes it from your catalog and inventory.'))return;
 button.disabled=true;status.textContent='Deleting part…';
 try{
  await saveWorkspace();if(workspaceConflict||JSON.stringify(workspaceData())!==workspaceSaved)throw Error('Save your pending changes before deleting this part. Reload if another administrator saved changes.');
  await shopCommand({action:'delete-product',partNumber:num});state.cart=state.cart.filter(l=>l.partId!==num);nav('#/admin/products');renderAdminProducts();
 }catch(e){status.textContent=e.message;}finally{button.disabled=false;}
};


deleteManualRecord=async function(kind,id,partNumber,button){
 if(!requireAdmin())return;const status=button.parentElement.querySelector('.manual-delete-status');
 if(workspaceSaving||commandBusy){status.textContent='Please wait for the current change to finish, then try again.';return;}
 const count=kind==='series'?PARTS.filter(p=>p.category===id).length:0;
 if(!confirm(button.textContent+'?'+(kind==='series'?' This removes '+id+' and its '+count+' unused parts.':' This permanently removes the saved entry.')))return;
 button.disabled=true;status.textContent='Deleting…';
 try{await saveWorkspace();if(workspaceConflict||JSON.stringify(workspaceData())!==workspaceSaved)throw Error('Save pending changes before deleting. Reload if another administrator saved changes.');
 await shopCommand({action:'delete-record',kind,id,...(kind==='price'?{partNumber}:{})});state.cart=state.cart.filter(l=>byNumber(l.partId));
 if(kind==='order'&&location.hash.includes('/orders/'+id))nav('#/admin/orders');renderRoute();
 }catch(e){status.textContent=e.message;}finally{button.disabled=false;}
};

async function savedAdminAction(body,form,statusSelector){
 if(!requireAdmin()||commandBusy||workspaceSaving)return false;const status=form.querySelector(statusSelector);const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);if(status)status.textContent='Saving…';
 try{await saveWorkspace();if(workspaceConflict||JSON.stringify(workspaceData())!==workspaceSaved)throw Error('Save pending changes or reload before continuing.');await shopCommand(body);return true;}catch(e){if(status)status.textContent=e.message;return false;}finally{buttons.forEach(b=>b.disabled=false);}
}
billingEditorHtml=function(o){const paid=o.amountPaidCents??(o.paymentStatus==='PAID'?o.totalCents:0),refunded=(o.refunds||[]).filter(r=>r.status==='succeeded').reduce((n,r)=>n+r.amountCents,0),refundable=Math.max(0,paid-refunded),history=(o.refunds||[]).map(r=>`<li>${esc(r.id)} · ${fmt(r.amountCents)} · ${esc(r.status)}</li>`).join('');return originalBillingEditor(o)+(state.user?.role==='ADMIN'?`<section class="card order-job" id="cancellationReview"><h2>Cancellation & refund review</h2><div class="job-fields"><p><strong>Collected</strong><br>${fmt(paid)}</p><p><strong>Confirmed refunds</strong><br>${fmt(refunded)}</p><p><strong>Retained</strong><br>${fmt(refundable)}</p></div>${history?`<ul>${history}</ul>`:''}${o.cancellationReview?.status==='REQUESTED'?`<p role="status">${esc(o.cancellationReview.action)} requested for ${fmt(o.cancellationReview.amountCents)}. Complete the refund in Whop, then record the verified result below.</p><form onsubmit="event.preventDefault();confirmOrderRefund('${esc(o.id)}',this)"><label>Whop refund ID<input class="field" name="refundId" required/></label><label>Whop payment ID<input class="field" name="paymentId" value="${esc(o.paymentReference||'')}" required/></label><label>Verified amount ($)<input class="field" name="amount" type="number" min="0.01" step="0.01" value="${(o.cancellationReview.amountCents/100).toFixed(2)}" required/></label><label>Reason<textarea class="field" name="reason" required maxlength="1000">${esc(o.cancellationReview.reason||'')}</textarea></label><button class="btn btn-primary">Record verified refund</button><p class="refund-status" role="status"></p></form>`:!o.cancelled?`<form onsubmit="event.preventDefault();requestOrderCancellation('${esc(o.id)}',this)"><label>Resolution<select class="field" name="resolution"><option value="refund">Refund payment</option><option value="retain">Cancel and retain payment</option><option value="unpaid">Cancel unpaid order</option></select></label><label>Refund amount ($)<input class="field" name="amount" type="number" min="0.01" step="0.01" max="${(refundable/100).toFixed(2)}" value="${(refundable/100).toFixed(2)}"/></label><label>Required reason<textarea class="field" name="reason" required maxlength="1000"></textarea></label><label class="retain-confirm"><input type="checkbox" name="confirmRetain"/> I confirm that the collected payment will be retained.</label><button class="btn btn-outline">Review cancellation</button><p class="refund-status" role="status"></p></form>`:`<p>This order is cancelled. ${o.cancellationReview?.action==='RETAIN_PAYMENT'?'Payment was retained.':'Financial history is preserved.'}</p>`}</section>`:'');};
async function requestOrderCancellation(id,form){if(!form.reportValidity())return;const f=new FormData(form),resolution=f.get('resolution'),reason=String(f.get('reason')).trim(),amountCents=Math.round(Number(f.get('amount'))*100);let body;if(resolution==='refund')body={action:'request-refund',orderId:id,amountCents,reason};else if(resolution==='retain'){if(!f.get('confirmRetain')){form.querySelector('.refund-status').textContent='Confirm that payment will be retained.';return;}body={action:'cancel-without-refund',orderId:id,reason,confirmation:'RETAIN PAYMENT'};}else body={action:'cancel-unpaid-order',orderId:id,reason};if(await savedAdminAction(body,form,'.refund-status'))renderRoute();}
async function confirmOrderRefund(id,form){if(!form.reportValidity())return;const f=new FormData(form),body={action:'confirm-refund',orderId:id,refundId:String(f.get('refundId')).trim(),paymentId:String(f.get('paymentId')).trim(),amountCents:Math.round(Number(f.get('amount'))*100),status:'succeeded',reason:String(f.get('reason')).trim()};if(await savedAdminAction(body,form,'.refund-status'))renderRoute();}
cancelOrder=function(id){nav('#/orders/'+encodeURIComponent(id));renderOrderDetail(id);document.getElementById('cancellationReview')?.scrollIntoView({block:'start'});};
reinstateOrder=function(id){const o=findOrder(id);if(o&&(o.refunds||[]).some(r=>r.status==='succeeded')){workspaceStatus('An order with a confirmed refund cannot be reinstated. Create a new order instead.',true);return;}workspaceStatus('Cancelled orders remain closed to preserve payment and audit history.',true);};
saveInvoiceDetails=async function(id,form,close=false){if(!form.reportValidity())return;const f=new FormData(form);if(await savedAdminAction({action:'record-payment',orderId:id,amountPaidCents:Math.round(Number(f.get('paid'))*100),method:String(f.get('method')),reference:String(f.get('reference')),dueDate:String(f.get('due')),close},form,'.billing-status'))renderRoute();};
async function resolveWarranty(orderId,requestId,form){const response=form.elements.response.value.trim();if(!response){form.querySelector('.resolution-status').textContent='Describe how the claim was resolved before closing it.';form.elements.response.focus();return;}if(!confirm('Resolve this request and share the outcome with the shop?'))return;if(await savedAdminAction({action:'resolve-request',orderId,requestId,response},form,'.resolution-status'))renderRoute();}
setPaymentStatus=function(id,status){if(!requireAdmin()||findOrder(id)?.paymentStatus===status)return;nav('#/orders/'+encodeURIComponent(id));renderOrderDetail(id);document.getElementById('invoicePayment')?.scrollIntoView({block:'start'});};

let whopElementsLoader=null;const whopPaymentMounts=new Map();
function loadWhopElements(){if(typeof window.WhopElements==='function')return Promise.resolve(window.WhopElements);if(whopElementsLoader)return whopElementsLoader;whopElementsLoader=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.whop.com/elements/amber/elements.js';script.dataset.whopElements='';script.async=true;script.onload=()=>typeof window.WhopElements==='function'?resolve(window.WhopElements):reject(Error('Secure payment form did not initialize.'));script.onerror=()=>reject(Error('Secure payment form is unavailable.'));document.head.append(script);});return whopElementsLoader;}
function validWhopSession(session){return /^biz_[A-Za-z0-9]+$/.test(session?.accountId||'')&&session.currency==='usd'&&Number.isSafeInteger(session.amount)&&session.amount>0&&typeof session.reference==='string'&&session.reference.length>=8&&session.reference.length<=100;}
function showWhopFallback(section,message){section.querySelector('.payment-checkout-status').textContent=message;section.querySelector('.whop-hosted-fallback').hidden=false;const button=section.querySelector('.whop-pay-button');button.hidden=true;}
async function mountInvoicePayment(id){const section=document.querySelector(`.whop-invoice-payment[data-whop-order="${CSS.escape(id)}"]`);if(!section||section.dataset.mounting==='true'||section.dataset.mounted==='true')return;section.dataset.mounting='true';const key=String(id).replace(/[^A-Za-z0-9_-]/g,''),status=section.querySelector('.payment-checkout-status'),button=section.querySelector('.whop-pay-button');let reserved=false;try{await loadWhopElements();if(!section.isConnected)return;const session=await api({action:'payment-session',orderId:id});reserved=true;if(session.status==='processing'){button.hidden=true;status.textContent='Payment is processing. This invoice will update after Whop confirms it.';section.dataset.mounted='true';return;}if(!validWhopSession(session))throw Error('Secure payment configuration is invalid.');const billing=session.billingDetails||{};if(!billing.email||!billing.name||!billing.address?.line1||!billing.address?.country)throw Error('Add your billing name and address in Shop details before paying online.');const existing=whopPaymentMounts.get(id);if(existing?.section!==section)existing?.payments?.destroy?.();const elements=window.WhopElements(),returnUrl=location.origin+location.pathname+'#/orders/'+encodeURIComponent(id)+'/invoice';const payments=elements.payments.create({accountId:session.accountId,currency:session.currency,amount:session.amount,returnUrl,onLoadingChange:loading=>{if(section.isConnected&&loading){button.disabled=true;button.textContent='Loading secure payment…';}}});payments.create('payment',{onChange:event=>{if(!section.isConnected)return;button.disabled=!event.complete;button.textContent='Pay '+fmt(session.amount);status.textContent=event.complete?'Payment details are ready.':'Complete your payment details.';},onError:event=>{if(section.isConnected)status.textContent=event?.message||'Check your payment details and try again.';}}).mount('#payments-payment-'+key);payments.create('branding').mount('#payments-branding-'+key);whopPaymentMounts.set(id,{section,elements,payments,session,billing});section.dataset.mounted='true';status.textContent='Choose a payment method to continue.';}catch(e){if(section.isConnected){if(reserved){button.hidden=true;status.textContent=(e.message||'Secure payment form is unavailable.')+' Contact Converter Express before trying another payment.';}else showWhopFallback(section,e.message||'Secure payment form is unavailable.');}}finally{section.dataset.mounting='false';}}
async function payInvoiceHosted(id,button){const section=button.closest('.whop-invoice-payment'),status=section.querySelector('.payment-checkout-status');button.disabled=true;status.textContent='Opening secure checkout…';try{const r=await api({action:'payment-checkout',orderId:id});const url=new URL(r.url);if(url.protocol!=='https:'||!(url.hostname==='whop.com'||url.hostname.endsWith('.whop.com')))throw Error('Invalid checkout address');location.assign(url.href);}catch(e){status.textContent=e.message;button.disabled=false;}}
async function refreshPaidInvoice(id){for(let attempt=0;attempt<5;attempt++){await new Promise(resolve=>setTimeout(resolve,1500));try{await loadRemote();if(findOrder(id)?.paymentStatus==='PAID'){renderOrderDetail(id);return true;}}catch{}}return false;}
async function payInvoice(id,button){const mounted=whopPaymentMounts.get(id),section=button.closest('.whop-invoice-payment'),status=section.querySelector('.payment-checkout-status');if(!mounted||mounted.section!==section)return;button.disabled=true;status.textContent='Securing your payment details…';try{const token=await mounted.payments.createConfirmationToken({billingDetails:mounted.billing});if(!/^ctok_[A-Za-z0-9]+$/.test(token?.confirmationToken||''))throw Error('Payment details could not be secured.');status.textContent='Confirming payment…';const confirmed=await api({action:'payment-confirm',orderId:id,reference:mounted.session.reference,confirmationToken:token.confirmationToken});if(typeof confirmed.clientSecret!=='string'||!confirmed.clientSecret.startsWith('pay_'))throw Error('Payment confirmation was incomplete.');const outcome=await mounted.elements.payments.handleNextAction({clientSecret:confirmed.clientSecret,returnUrl:location.origin+location.pathname+'#/orders/'+encodeURIComponent(id)+'/invoice'});if(outcome.lastPaymentError)throw Error(outcome.lastPaymentError.message||'Whop could not complete the payment.');if(outcome.redirected)return;status.textContent=['paid','succeeded'].includes(outcome.status)?'Payment received. Confirming your invoice…':'Payment is processing. This invoice will update after Whop confirms it.';if(await refreshPaidInvoice(id))return;button.hidden=true;}catch(e){if(e?.code==='payment_request_cancelled'){status.textContent='Payment canceled. You can try again when ready.';}else status.textContent=e.message||'Payment could not be completed.';button.disabled=false;}}
const originalRequestUpdate=updateServiceRequest;
updateServiceRequest=function(orderId,id,form){if(form.elements.status.value==='Resolved'&&findOrder(orderId)?.serviceRequests?.find(r=>r.id===id)?.status!=='Resolved')return resolveWarranty(orderId,id,form);return originalRequestUpdate(orderId,id,form);};
