import {AppError} from './business.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((n||0)/100);
export function orderEmail(order,kind){
 if(!['confirmation','invoice'].includes(kind)||!order||!Array.isArray(order.lines))throw new AppError('Invalid order email');
 if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(order.shopEmail||''))throw new AppError('The saved order has an invalid recipient email');
 const title=kind==='invoice'?'Your invoice':'We received your order';
 const subject=`${kind==='invoice'?'Invoice':'Order received'} ${String(order.invoiceNumber).replace(/[\r\n]/g,'')} · Converter Express`;
 const href='https://www.converterexpress.net/#/orders/'+encodeURIComponent(order.id)+(kind==='invoice'?'/invoice':'');
 const rows=[['Subtotal',order.subtotalCents],['Discount',-order.discountCents],['Delivery',order.shippingCents],['Tax',order.taxCents],['Card fee',order.cardFeeCents],['Total',order.totalCents]];if(kind==='invoice'){const paid=order.paymentStatus==='PAID'?order.totalCents:order.amountPaidCents||0;rows.push(['Amount paid',paid],['Balance due',Math.max(0,order.totalCents-paid)]);}
 const address=order.fulfillment?.address;const destination=address?[address.line1,address.line2,address.city,address.state,address.postalCode].filter(Boolean).join(', '):'See your account for fulfillment details.';
 const status=order.cancelled?'Cancelled':order.paymentStatus==='PAID'?'Paid':order.paymentStatus==='PARTIAL'?'Partially paid':'Payment outstanding';
 const content=`<p style="color:#b23815;font-size:11px;letter-spacing:1.5px;font-weight:bold">${kind==='invoice'?'YOUR INVOICE':'YOUR ORDER'}</p><h1 style="font-size:28px;line-height:1.2">${title}</h1><p style="line-height:1.7;color:#535e67">Hello ${esc(order.shopName)},<br>${kind==='invoice'?'Here are the details of your invoice.':'Thank you for ordering with Converter Express. Check your account for the latest order and delivery status.'}</p><p><strong>${esc(order.invoiceNumber)}</strong><br><span style="font-size:13px;color:#535e67">${esc(status)}${order.poNumber?' · PO '+esc(order.poNumber):''}</span></p><table width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;font-size:13px"><thead><tr style="background:#f1f2ee"><th align="left">Part</th><th align="right">Qty</th><th align="right">Amount</th></tr></thead><tbody>${order.lines.map(l=>`<tr><td style="border-bottom:1px solid #e5e7e1;word-break:break-word">${esc(l.partId)}<br><span style="font-size:11px;color:#69727b">${esc(l.name)}</span></td><td align="right">${esc(l.quantity)}</td><td align="right" style="white-space:nowrap">${money(l.priceCents*l.quantity)}</td></tr>`).join('')}</tbody></table><table width="100%" cellpadding="7" cellspacing="0" style="margin:16px 0;font-size:13px">${rows.map(([label,value])=>`<tr><td>${label}</td><td align="right" style="font-weight:${label==='Total'?'bold':'normal'}">${money(value)}</td></tr>`).join('')}</table><p style="font-size:13px;line-height:1.7"><strong>Delivery details</strong><br>${esc(destination)}</p><p style="margin:28px 0"><a href="${href}" style="display:inline-block;padding:15px 22px;background:#ce4018;color:#fff;font-size:14px;font-weight:bold;border-radius:6px;text-decoration:none">View ${kind==='invoice'?'invoice':'order'} →</a></p><p style="font-size:12px;color:#69727b;line-height:1.7">Sign in with your shop account to view this order. This email reflects the saved order when the email was prepared; your account shows its current status.</p>`;
 const html=`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(subject)}</title></head><body style="margin:0;background:#efefeb;font-family:Arial,Helvetica,sans-serif;color:#1b2024"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:580px"><tr><td style="padding:28px;background:#171d21;color:white;border-bottom:4px solid #e24c23;font-size:21px;font-weight:bold">CONVERTER <span style="color:#ff8a60">EXPRESS</span></td></tr><tr><td style="padding:28px;background:white">${content}</td></tr><tr><td style="padding:24px 28px;background:#f7f7f4;font-size:12px;line-height:1.8">Questions? <a style="color:#b23815" href="https://www.converterexpress.net/#/contact">Contact Converter Express</a><br>Sacramento · Stockton · Bay Area</td></tr></table></td></tr></table></body></html>`;
 const text=[title,order.invoiceNumber,`Shop: ${order.shopName}`,`Payment: ${status}`,...order.lines.map(l=>`${l.partId} | ${l.quantity} × ${money(l.priceCents)} | ${money(l.quantity*l.priceCents)}`),...rows.map(([k,v])=>`${k}: ${money(v)}`),`Delivery: ${destination}`,`View securely: ${href}`,'Contact: https://www.converterexpress.net/#/contact'].join('\n');
 return {from:'Converter Express <accounts@converterexpress.co>',to:[order.shopEmail],subject,html,text};
}
export async function sendOrderEmail({rpc,apiKey,orderId,kind,fetcher=fetch}){
 if(!apiKey)return {status:'not_configured',issue:'Order email sending is not configured.'};
 const prepared=await rpc('ce_email_prepare',{oid:orderId,mail_kind:kind});
 if(prepared.status==='accepted')return {status:'accepted',providerId:prepared.provider_id};
 const claim=crypto.randomUUID();const row=await rpc('ce_email_claim',{oid:orderId,mail_kind:kind,content:prepared.payload||orderEmail(prepared.snapshot,kind),claim_id:claim});
 if(!row)return {status:'pending_review',issue:'Another send is running, or an earlier attempt needs review before retrying.'};
 let status='unknown',provider=null,issue='Sending could not be confirmed. Retry within 23 hours or check Resend before resending.';
 try{const response=await fetcher('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+apiKey,'Content-Type':'application/json','Idempotency-Key':'ce-'+kind+'-'+orderId},body:JSON.stringify(row.payload),signal:AbortSignal.timeout(12000)});const result=await response.json();if(response.ok&&typeof result.id==='string'){status='accepted';provider=result.id;issue=null;}else if(response.status>=400&&response.status<500&&![408,409,429].includes(response.status)){status='failed';issue='Email provider rejected the request. Check sender verification and configuration, then retry.';}}
 catch{} // Never expose provider errors, credentials, or customer data in logs.
 await rpc('ce_email_finish',{oid:orderId,mail_kind:kind,claim_id:claim,outcome:status,provider,problem:issue});
 return {status,providerId:provider,issue};
}
