import {AppError} from './business.mjs';
const fail=(m,s=400)=>{throw new AppError(m,s)};
export function invoiceBalance(o){if(!o||o.cancelled||o.paymentStatus==='PAID')fail('This invoice is not payable');if(o.paymentStatus==='PARTIAL'&&!Number.isSafeInteger(o.amountPaidCents))fail('Ask us to confirm the invoice balance');const paid=o.amountPaidCents||0,balance=o.totalCents-paid;if(!Number.isSafeInteger(balance)||balance<=0)fail('This invoice has no balance due');return {paid,balance};}
export function checkoutPayload(o,companyId,reference){const {balance}=invoiceBalance(o);if(!/^biz_[A-Za-z0-9]+$/.test(companyId||''))fail('Whop is not configured',503);return {account_id:companyId,mode:'payment',plan:{account_id:companyId,currency:'usd',plan_type:'one_time',initial_price:balance/100,title:'Converter Express '+o.invoiceNumber,description:'Invoice payment',stock:1,unlimited_stock:false,force_create_new_plan:true,visibility:'hidden'},metadata:{ce_order_id:o.id,ce_reference:reference},redirect_url:'https://www.converterexpress.net/#/orders/'+encodeURIComponent(o.id)+'/invoice'};}
export function paymentElementConfig(o,companyId){const {balance}=invoiceBalance(o);if(!/^biz_[A-Za-z0-9]+$/.test(companyId||''))fail('Whop is not configured',503);return {accountId:companyId,currency:'usd',amount:balance};}
export function verifyReservationPayment(p,r,companyId){if(!/^pay_[A-Za-z0-9]+$/.test(p?.id||'')||p.status!=='paid'||p.currency!=='usd'||p.account_id!==companyId||p.auto_refunded||p.refunded_at)fail('Payment has not been verified');if(p.metadata?.ce_reservation_id!==r.id||p.metadata?.ce_reference!==r.paymentReference)fail('Payment does not match this checkout');const amount=cents(p.total);if(amount!==r.amountCents)fail('Payment does not match the checkout amount');return p;}
export function elementPaymentPayload(o,companyId,reference,confirmationToken,email){const config=paymentElementConfig(o,companyId);if(!/^ctok_[A-Za-z0-9]+$/.test(confirmationToken||''))fail('Invalid payment confirmation');if(typeof reference!=='string'||reference.length<8||reference.length>100)fail('Invalid payment reference');if(typeof email!=='string'||email.length>254||!email.includes('@'))fail('Invalid payment email');return {account_id:companyId,confirmation_token:confirmationToken,email,plan:{currency:config.currency,plan_type:'one_time',initial_price:config.amount/100,title:'Converter Express '+o.invoiceNumber,description:'Invoice payment',force_create_new_plan:true,visibility:'hidden'},metadata:{ce_order_id:o.id,ce_reference:reference}};}
export function reservationPaymentPayload(r,companyId,confirmationToken,email){if(!/^biz_[A-Za-z0-9]+$/.test(companyId||''))fail('Whop is not configured',503);if(!/^ctok_[A-Za-z0-9]+$/.test(confirmationToken||''))fail('Invalid payment confirmation');if(!Number.isSafeInteger(r.amount_cents)||r.amount_cents<=0||typeof r.payment_reference!=='string'||typeof email!=='string'||!email.includes('@'))fail('Invalid checkout payment');return {account_id:companyId,confirmation_token:confirmationToken,email,plan:{currency:'usd',plan_type:'one_time',initial_price:r.amount_cents/100,title:'Converter Express order',description:'Parts order payment',force_create_new_plan:true,visibility:'hidden'},metadata:{ce_reservation_id:r.id,ce_reference:r.payment_reference}};}
export function safeCheckoutUrl(url){const u=new URL(url);if(u.protocol!=='https:'||!(u.hostname==='whop.com'||u.hostname.endsWith('.whop.com')))fail('Whop returned an invalid checkout address',502);return u.href;}
async function request(path,apiKey,body,fetchImpl,apiVersion){if(!apiKey)fail('Whop is not configured',503);const r=await fetchImpl('https://api.whop.com/api/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+apiKey,'Content-Type':'application/json','Api-Version-Date':apiVersion,...(body?.metadata?.ce_reference?{'Idempotency-Key':body.metadata.ce_reference}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(20000)});if(!r.ok)fail('Whop could not complete the request. Please contact us.',502);return r.json();}
export async function whopRequest(path,apiKey,body,fetchImpl=fetch){return request(path,apiKey,body,fetchImpl,'2026-09-29');}
export async function whopPaymentRequest(path,apiKey,body,fetchImpl=fetch){return request(path,apiKey,body,fetchImpl,'2026-10-08');}
export async function verifyWhopWebhook(raw,headers,secret,now=Date.now()){
 if(!secret)fail('Webhook is not configured',503);const id=headers.get('webhook-id'),ts=headers.get('webhook-timestamp'),sig=headers.get('webhook-signature');if(!id||id.length>200||!/^\d+$/.test(ts||'')||Math.abs(now/1000-Number(ts))>300||!sig||raw.length>500000)fail('Invalid webhook signature',401);
 const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);const bytes=new TextEncoder().encode(id+'.'+ts+'.'+raw);let valid=false;for(const token of sig.split(' ')){const [v,s]=token.split(',');if(v!=='v1'||!s)continue;try{const b=Uint8Array.from(atob(s),x=>x.charCodeAt(0));if(await crypto.subtle.verify('HMAC',key,b,bytes))valid=true;}catch{}}
 if(!valid)fail('Invalid webhook signature',401);return JSON.parse(raw);
}
function cents(m){if(!m||m.currency!=='usd'||typeof m.amount!=='string'||!/^\d+(\.\d{1,2})?$/.test(m.amount))fail('Invalid payment amount');const [a,b='']=m.amount.split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));if(!Number.isSafeInteger(n))fail('Invalid payment amount');return n;}
export function applyWhopPayment(source,p,companyId){
 if(!/^pay_[A-Za-z0-9]+$/.test(p.id||'')||p.status!=='paid'||p.currency!=='usd'||p.account_id!==companyId)fail('Payment has not been verified');const data=structuredClone(source),o=data.orders.find(o=>o.id===p.metadata?.ce_order_id);if(!o)fail('Invoice not found',404);const c=o.paymentCheckout,sourceMatches=c?.mode==='element'?c.id===p.id:c?.id===p.checkout_configuration_id;if(!c||c.reference!==p.metadata.ce_reference||!sourceMatches)fail('Payment does not match this checkout');const amount=cents(p.total);if(amount!==c.amountCents)fail('Payment does not match the invoice amount');if(p.auto_refunded||p.refunded_at)fail('Payment has been refunded');
 if((o.whopReceipts||[]).some(r=>r.id===p.id))return {data,duplicate:true};const at=new Date().toISOString();o.whopReceipts=[...(o.whopReceipts||[]),{id:p.id,amountCents:amount,at}];
 if(o.cancelled||(o.amountPaidCents||0)!==c.beforePaidCents||o.totalCents!==c.beforePaidCents+amount){o.paymentReview='Whop payment received; invoice changed. Reconcile in Whop before editing this invoice.';c.status='review';return {data,review:true};}
 o.amountPaidCents=o.totalCents;o.paymentStatus='PAID';o.paymentMethod='Whop';o.paymentReference=p.id;o.invoiceClosedAt=at;c.status='paid';data.crm.activities.push({id:crypto.randomUUID(),accountId:data.accounts.find(a=>a.email===o.shopEmail)?.id||null,type:'Payment',text:o.invoiceNumber+' · Whop payment verified · Closed',at});return {data};
}
