// Isolated browser workflow: real application code, explicit in-memory Auth/API mocks.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/khaledwahby/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const {validate,project}=await import('../../supabase/functions/_shared/business.mjs');
let revision=1,db={accounts:[{id:'acct-shop-001',email:'shop@example.com',role:'CUSTOMER',status:'APPROVED',shopName:'Release test shop',contactName:'Test',phone:'5550100000',addressLine1:'1 Test Street',addressLine2:'',city:'Sacramento',state:'CA',postalCode:'95814'}],orders:[],products:[{partNumber:'201010',name:'Part 201010',category:'Universal Converters — 201 Series',description:'Test',priceCents:20000,pricePending:false,costCents:9000,inStock:true}],discountCodes:[{code:'WELCOME50',type:'AMOUNT',value:50,active:true}],storeSettings:{shippingFlatCents:0,taxRatePercent:0,actualShippingCostCents:0,pickupAvailable:false,serviceArea:'Sacramento',customSeries:[]},crm:{quotes:[],tasks:[],purchases:[],inventory:{},activities:[]}};
const user={id:'staff',email:'staff@example.test',admin:true,aal:'aal1'},failures=[];
const b=await chromium.launch({headless:true,channel:'chrome',args:['--disable-gpu']});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.dismiss());
await p.route('**/config.js',r=>r.fulfill({contentType:'text/javascript',body:"window.CE_CONFIG={supabaseUrl:'https://mock.supabase.co',publishableKey:'sb_publishable_mock'};"}));
await p.route('**/vendor/supabase-2.117.2.js',r=>r.fulfill({contentType:'text/javascript',body:"window.supabase={createClient(){return {auth:{async getSession(){return {data:{session:{access_token:'mock'}}}},onAuthStateChange(){},async signOut(){return {error:null}}}}}};"}));
await p.route('https://mock.supabase.co/functions/v1/crm-api',async r=>{const body=r.request().postDataJSON();try{if(body.action==='admin-save'){validate(body.data);assert.equal(body.revision,revision);db=body.data;revision++;return r.fulfill({json:{revision}});}assert.equal(body.action,'bootstrap');return r.fulfill({json:{...project(db,user),revision}});}catch(e){failures.push(e.message);return r.fulfill({status:400,json:{error:e.message}});}});
await p.goto('http://127.0.0.1:8778/converter-express_1.html#/admin/dashboard');await p.waitForFunction(()=>workspaceReady&&!workspaceSaving);
const go=async route=>{await p.evaluate(route=>{location.hash='#/admin/'+route;renderRoute()},route);await p.waitForTimeout(150);};
await go('accounts/acct-shop-001');await p.locator('form').filter({has:p.locator('[name="text"]')}).locator('[name="text"]').fill('Called shop about replenishment');await p.getByRole('button',{name:'Log activity',exact:true}).click();assert.equal(await p.evaluate(()=>crmData().activities.filter(a=>a.text==='Called shop about replenishment').length),1);
await p.locator('[name="days"]').selectOption('30');await p.getByRole('button',{name:'Save terms',exact:true}).click();await p.locator('[name="part"]').fill('201010');await p.locator('[name="price"]').fill('150');await p.getByRole('button',{name:'Save price',exact:true}).click();
await go('purchasing');await p.getByText('Create purchase order',{exact:true}).first().click();await p.locator('[name="supplier"]').fill('Test supplier');await p.locator('[name="expected"]').fill('2026-10-10');await p.locator('[name="lines"]').fill('201010, 10');await p.getByRole('button',{name:'Create purchase order',exact:true}).click();await p.locator('[name="line0"]').fill('6');await p.getByRole('button',{name:'Receive stock',exact:true}).click();assert.deepEqual(await p.evaluate(()=>[crmData().inventory['201010'].onHand,crmIncoming('201010')]),[6,4]);await p.locator('[name="line0"]').fill('4');await p.getByRole('button',{name:'Receive stock',exact:true}).click();assert.deepEqual(await p.evaluate(()=>[crmData().inventory['201010'].onHand,crmIncoming('201010')]),[10,0]);
await go('quotes');await p.getByText('Create a quote',{exact:true}).click();await p.locator('#quoteForm [name="accountId"]').selectOption('acct-shop-001');await p.locator('#quotePart').fill('201010');await p.locator('#quoteQty').fill('2');await p.getByRole('button',{name:'Add part',exact:true}).click();await p.getByRole('button',{name:'Save quote',exact:true}).click();await p.locator('select[aria-label^="Status for"]').selectOption('Accepted');await p.getByRole('button',{name:'Schedule follow-up',exact:true}).click();await p.locator('[name="owner"]').fill('Operations');await p.getByRole('button',{name:'Create task',exact:true}).click();assert.ok(await p.evaluate(()=>crmData().tasks[0].quoteId));await p.getByRole('button',{name:'Mark complete',exact:true}).click();assert.equal(await p.evaluate(()=>crmData().tasks[0].done),true);
await go('quotes');await p.getByRole('button',{name:'Convert to order',exact:true}).click();await p.waitForTimeout(100);let orderId=await p.evaluate(()=>crmData().quotes[0].orderId);assert.ok(orderId);assert.deepEqual(await p.evaluate(id=>{const o=findOrder(id);return[o.lines[0].priceCents,crmReserved('201010'),crmAvailable('201010'),o.dueDate===crmDateDays(crmToday(),30)]},orderId),[15000,2,8,true]);
await go('dispatch');let row=p.locator('.crm-quote').filter({has:p.locator('a[href="#/orders/'+orderId+'"]')});await row.locator('[name="date"]').fill('2026-10-03');await row.locator('[name="area"]').selectOption('Sacramento');await row.locator('[name="driver"]').fill('Driver A');await row.getByRole('button',{name:'Save assignment',exact:true}).click();await row.getByRole('button',{name:'Mark out for delivery',exact:true}).click();assert.deepEqual(await p.evaluate(()=>[crmData().inventory['201010'].onHand,crmReserved('201010')]),[8,0]);await row.locator('[name="receiver"]').fill('Shop manager');await row.getByRole('button',{name:'Confirm delivered',exact:true}).click();assert.deepEqual(await p.evaluate(id=>[findOrder(id).fulfillmentStage,crmData().inventory['201010'].onHand,findOrder(id).dispatch.receiver],orderId),['DELIVERED',8,'Shop manager']);
await p.waitForFunction(()=>!workspaceSaving&&workspaceSaved===JSON.stringify(workspaceData()));await p.reload();await p.waitForFunction(()=>workspaceReady&&!workspaceSaving);assert.deepEqual(await p.evaluate(()=>[crmData().quotes.length,crmData().tasks.length,crmData().purchases[0].status,crmData().inventory['201010'].onHand]),[1,1,'Received',8]);
for(const width of [1440,390,320]){await p.setViewportSize({width,height:1000});for(const route of ['dashboard','quotes','tasks','dispatch','inventory','purchasing','accounts/acct-shop-001']){await go(route);assert.equal(await p.locator('.admin-shared-tabs a').count(),12);const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,route+' overflows '+width);}if(width===390)await p.screenshot({path:'/tmp/crm-mobile.png',fullPage:true});}
await p.setViewportSize({width:1440,height:1000});await go('tasks');await p.screenshot({path:'/tmp/crm-tasks-final.png'});await p.evaluate(d=>applyRemote(d),{...project(db,{id:'acct-shop-001',email:'shop@example.com',admin:false,aal:'aal1'}),revision});await p.evaluate(()=>{state.cart=[];addToCart('201010',1);renderCart();});assert.equal(await p.evaluate(()=>checkoutSubtotalCents()),15000);assert.ok((await p.locator('#app').innerText()).includes('150.00'));assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);console.log('PASS: activity, terms, negotiated prices, partial purchasing, quote follow-up, conversion, reservations, dispatch, delivery confirmation, reload persistence, all routes at 1440/390/320, cart pricing.');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
