const fs=require('node:fs'),path=require('node:path');
const origin='https://converterexpress.net';
const pages=require('../seo/pages.json');
const esc=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const links=pages.map(p=>`<a href="/${p.slug}">${esc(p.heading)}</a>`).join('');
const organization={'@context':'https://schema.org','@type':'Organization','@id':origin+'/#organization',name:'Converter Express',url:origin+'/',description:'Catalytic converter supplier for automotive shops in Sacramento, Stockton, and the Bay Area.',areaServed:['Sacramento','Stockton','San Francisco Bay Area']};
const style=`*{box-sizing:border-box}body{margin:0;background:#f3f3ef;color:#171a1e;font:16px/1.75 system-ui,sans-serif}a{color:inherit;text-underline-offset:5px}header,main,footer{max-width:1160px;margin:auto;padding:28px}header{display:flex;justify-content:space-between;gap:24px;border-bottom:1px solid #d5d7d8}header>a{font-weight:850;text-decoration:none}nav{display:flex;flex-wrap:wrap;gap:22px}main{padding-top:80px;padding-bottom:80px}.kicker{color:#bf3612;letter-spacing:.15em;font-size:12px;font-weight:700}h1{font-size:clamp(36px,6vw,68px);line-height:1.05;letter-spacing:-.045em;max-width:850px;margin:22px 0}h2{font-size:26px;line-height:1.25;letter-spacing:-.025em;margin:0}.intro{max-width:780px;font-size:20px;color:#59606a;margin:28px 0 48px}.cta{display:inline-block;background:#d94218;color:white;padding:13px 22px;border-radius:8px;text-decoration:none;font-weight:650}section{display:grid;grid-template-columns:1fr 1.6fr;gap:48px;padding:38px 0;border-top:1px solid #d5d7d8}section p{margin:0 0 18px;color:#535b65}section a{font-weight:650}footer{border-top:1px solid #d5d7d8;font-size:14px}footer nav{margin:18px 0}footer small{color:#616773}@media(max-width:650px){header{flex-direction:column;gap:14px}main{padding-top:45px}section{grid-template-columns:1fr;gap:16px}.intro{font-size:18px}nav{gap:12px 22px}}`;
function metadata(title,description,url){return `<title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${origin}/hero-v2.png"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify(organization)}</script>`;}
module.exports=function(output){
 for(const p of pages){const url=origin+'/'+p.slug;fs.writeFileSync(path.join(output,p.slug+'.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${metadata(p.title,p.description,url)}<style>${style}</style></head><body><header><a href="/">CONVERTER EXPRESS</a><nav aria-label="Main navigation"><a href="/catalytic-converters">Converters</a><a href="/shop-delivery">Delivery</a><a href="/about-converter-express">About</a><a href="/#/login">Shop sign in</a></nav></header><main><div class="kicker">${p.kicker}</div><h1>${p.heading}</h1><p class="intro">${p.intro}</p><p><a class="cta" href="/#/register">Get $50 off your first order →</a></p>${p.sections.map(s=>`<section><h2>${s.heading}</h2><div><p>${s.text}</p><a href="${s.link}">${s.label} →</a></div></section>`).join('')}</main><footer><strong>Converter Express</strong><nav aria-label="More about Converter Express">${links}</nav><small>Serving shops in Sacramento, Stockton, and the Bay Area.</small></footer></body></html>`);}
 for(const file of ['index.html','converter-express_1.html']){const target=path.join(output,file);let html=fs.readFileSync(target,'utf8').replace('<html>','<html lang="en">').replace('<title>Converter Express Demo</title>',metadata('Catalytic Converters for Auto Shops | Converter Express','Wholesale catalytic converters with free same-day shop delivery in Sacramento, Stockton and the Bay Area. Get $50 off your first order after account approval.',origin+'/'));html=html.replace('<main id="app"></main>',`<main id="app"><section style="max-width:1100px;margin:auto;padding:48px 24px"><h1>Catalytic converters delivered to your shop</h1><p>Converter Express supplies Converter Unlimited catalytic converters to automotive shops in Sacramento, Stockton, and the Bay Area. Free same-day shop delivery and $50 off your first order after account approval.</p><nav aria-label="Learn about Converter Express">${links}</nav></section></main>`);fs.writeFileSync(target,html);}
 fs.writeFileSync(path.join(output,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+['/',...pages.map(p=>'/'+p.slug)].map(p=>`  <url><loc>${origin}${p}</loc></url>`).join('\n')+'\n</urlset>\n');
 fs.writeFileSync(path.join(output,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: ${origin}/sitemap.xml\n`);
};
