// Browser integration with explicit Auth/API mocks. This does NOT verify hosted Supabase Auth.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const assert=require('node:assert/strict');
(async()=>{const {project,command}=await import('../supabase/functions/_shared/business.mjs');let db={accounts:[{id:'user-a',email:'a@example.test',role:'CUSTOMER',status:'APPROVED',shopName:'Shop A',contactName:'A',phone:'1',addressLine1:'1 Road',city:'Sacramento',state:'CA',postalCode:'95814'}],orders:[],products:[{partNumber:'201010',name:'Part 201010',category:'Universal Converters — 201 Series',description:'Converter',priceCents:15000,pricePending:false,costCents:9000,inStock:true}],discountCodes:[{code:'WELCOME50',type:'AMOUNT',value:50,active:true}],storeSettings:{shippingFlatCents:0,taxRatePercent:0,actualShippingCostCents:0,pickupAvailable:false},crm:{quotes:[],tasks:[],purchases:[],inventory:{201010:{onHand:3,minimum:0}},activities:[]}},revision=1;const user={id:'user-a',email:'a@example.test',admin:true,aal:'aal1'};const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR',e.message)});await p.route('**/config.js',r=>r.fulfill({contentType:'text/javascript',body:"window.CE_CONFIG={supabaseUrl:'https://mock.supabase.co',publishableKey:'sb_publishable_mock'};"}));await p.route('**/vendor/supabase-2.117.2.js',r=>r.fulfill({contentType:'text/javascript',body:`window.supabase={createClient(){let cb;return {auth:{async getSession(){if(sessionStorage.getItem('test-recovery')){sessionStorage.removeItem('test-recovery');cb?.('PASSWORD_RECOVERY');}return {data:{session:sessionStorage.getItem('test-session')?{access_token:'mock-token'}:null}}},async signInWithPassword(){sessionStorage.setItem('test-session','yes');return {error:null}},async getUser(){return {data:{user:{id:'user-a',email:'a@example.test'}}}},onAuthStateChange(fn){cb=fn;return {}},async signOut(){sessionStorage.removeItem('test-session');cb?.('SIGNED_OUT');return {error:null}}}}}};`}));await p.route('https://mock.supabase.co/functions/v1/crm-api',async r=>{const body=r.request().postDataJSON(),signed=!!r.request().headers().authorization;try{let data;if(body.action==='order-email'){if(body.operation==='preview')data={to:'a@example.test',subject:'Saved invoice',html:'<h1>Saved invoice</h1>'};else if(body.operation==='status')data={configured:true,emails:db._mailSent?[{kind:'invoice',status:'accepted'}]:[]};else {db._mailSent=true;data={email:{status:'accepted'}};}}else if(body.action==='admin-save'){db=body.data;revision++;data={revision};}else if(body.action==='bootstrap')data={...project(db,signed?user:null),revision};else if(body.action==='fitment')data={results:[]};else if(body.action==='quote')data={quote:command(db,user,{...body,action:'order'}).result};else {const next=command(db,user,body);db=next.data;revision++;data={...project(db,user),revision,result:next.result};}await r.fulfill({json:data});}catch(e){await r.fulfill({status:e.status||400,json:{error:e.message}});}});
await p.goto('http://127.0.0.1:8778/converter-express_1.html#/login');await p.waitForFunction(()=>workspaceReady);await p.locator('#authEmail').fill(user.email);await p.locator('#authPassword').fill('test-password-only');await p.locator('#authForm button').click();await p.waitForFunction(()=>state.user?.role==='ADMIN');
await p.evaluate(()=>{state.accounts=[{id:'pending-test',shopName:'Example Auto & Repair',contactName:'Alex Shop',email:'shop@example.test',phone:'916 555 0100',addressLine1:'123 Example Road',city:'Sacramento',state:'CA',postalCode:'95814',status:'PENDING',licensePath:'test/license'}];nav('#/admin/accounts');renderAdminAccounts();});
assert.equal(await p.locator('.account-review-card').count(),1);assert.equal(await p.locator('.account-directory-row').count(),0);
await p.evaluate(()=>{window.openLicense=id=>window.testLicense=id});await p.getByRole('button',{name:'View business license'}).click();assert.equal(await p.evaluate(()=>window.testLicense),'pending-test');
await p.setViewportSize({width:1440,height:1050});await p.screenshot({path:'/tmp/ce-accounts-desktop.png',fullPage:true});
await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'/tmp/ce-accounts-mobile.png',fullPage:true});
await p.getByRole('button',{name:'Approve shop'}).click();assert.equal(await p.locator('.account-review-card').count(),0);assert.equal(await p.locator('.account-directory-row').count(),1);assert.match(await p.locator('.account-directory-row').innerText(),/APPROVED/);
await p.evaluate(()=>{state.accounts[0].status='PENDING';renderAdminAccounts();});await p.getByRole('button',{name:'Reject',exact:true}).click();assert.match(await p.locator('.account-directory-row').innerText(),/REJECTED/);
assert.deepEqual(errors,[]);console.log('PASS account review layout, license action, approval/rejection transitions, no duplicates, mobile width');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
