import test from 'node:test';
import assert from 'node:assert/strict';
import * as rules from '../supabase/functions/_shared/business.mjs';
const {command}=rules;
const admin={id:'admin',email:'admin@example.test',admin:true};
const fixture=()=>({accounts:[{id:'shop',email:'shop@example.test',role:'CUSTOMER',status:'APPROVED',savedParts:['P1','P2'],priceOverrides:{P1:12000,P2:13000}}],products:[{partNumber:'P1',name:'Part P1',category:'201',priceCents:12000,pricePending:false,costCents:5000,inStock:false},{partNumber:'P2',name:'Part P2',category:'202',priceCents:13000,pricePending:false,costCents:5000,inStock:false}],orders:[],discountCodes:[],storeSettings:{},crm:{inventory:{P1:{onHand:0,minimum:1}},quotes:[],purchases:[],tasks:[],activities:[]}});
const deletion={action:'delete-product',partNumber:'P1'};
test('only administrators can delete products',()=>{for(const user of [null,{id:'shop',email:'shop@example.test',admin:false}])assert.throws(()=>command(fixture(),user,deletion),e=>[401,403].includes(e.status));});
test('unused zero-stock part is removed with stale inventory and shop references',()=>{const old=fixture(),r=command(old,admin,deletion);assert.deepEqual(r.data.products.map(p=>p.partNumber),['P2']);assert.equal(r.data.crm.inventory.P1,undefined);assert.deepEqual(r.data.accounts[0].savedParts,['P2']);assert.deepEqual(r.data.accounts[0].priceOverrides,{P2:13000});assert.equal(old.products.length,2);assert.equal(r.data.crm.activities.at(-1).type,'Product');});
test('physical stock prevents deletion',()=>{const s=fixture();s.crm.inventory.P1.onHand=1;assert.throws(()=>command(s,admin,deletion),/stock/i);});
test('all saved order, quote and purchase references prevent deletion',()=>{for(const kind of ['orders','quotes','purchases']){const s=fixture(),records=kind==='orders'?s.orders:s.crm[kind];records.push({id:'old',cancelled:true,status:'Cancelled',lines:[{partId:'P1',partNumber:'P1',quantity:1}]});assert.throws(()=>command(s,admin,deletion),/order|quote|purchase/i);assert.equal(s.products.length,2);}});
test('deleting missing part fails and malformed inputs are rejected',()=>{assert.throws(()=>command(fixture(),admin,{...deletion,partNumber:'unknown'}),e=>e.status===404);assert.throws(()=>command(fixture(),admin,{...deletion,role:'ADMIN'}),/unexpected/i);});
test('workspace saves cannot bypass deletion protections',()=>{const validateProductRemovals=rules.validateProductRemovals;assert.equal(typeof validateProductRemovals,'function');const before=fixture();before.orders=[{lines:[{partId:'P1'}]}];const after=structuredClone(before);after.products=after.products.filter(p=>p.partNumber!=='P1');assert.throws(()=>validateProductRemovals(before,after),/order/i);const clean=fixture(),next=structuredClone(clean);next.products=next.products.filter(p=>p.partNumber!=='P1');assert.doesNotThrow(()=>validateProductRemovals(clean,next));});

test('a workspace save cannot add a reference while removing its product',()=>{const before=fixture(),next=structuredClone(before);next.products=next.products.filter(p=>p.partNumber!=='P1');next.crm.purchases.push({lines:[{partNumber:'P1'}]});assert.throws(()=>rules.validateProductRemovals(before,next),/purchase/i);});
