import test from 'node:test';import assert from 'node:assert/strict';import {orderEmail,sendOrderEmail} from '../supabase/functions/_shared/order-email.mjs';
const o={id:'order1',invoiceNumber:'INV-TEST',shopEmail:'buyer@example.test',shopName:'Shop <script>x</script>',paymentStatus:'UNPAID',lines:[{partId:'201010',name:'A & B',quantity:2,priceCents:10000,costCents:3000}],subtotalCents:20000,discountCents:5000,shippingCents:0,taxCents:1200,totalCents:16200,cardFeeCents:0,fulfillment:{address:{line1:'123 Test Rd',city:'Sacramento',state:'CA',postalCode:'95814'}},crmNotes:'PRIVATE'};
test('HTML/text use saved totals, escape content and exclude internal costs',()=>{for(const kind of ['confirmation','invoice']){const m=orderEmail(o,kind);assert.deepEqual(m.to,[o.shopEmail]);assert(m.html.includes('$162.00'));assert(!m.html.includes('<script>'));assert(!m.html.includes('PRIVATE'));assert(!m.html.includes('$30.00'));assert(m.text.includes('Payment outstanding'));assert(m.html.includes('https://converterexpress.net/#/orders/order1'));}});
test('rejects invalid recipient and kind',()=>{assert.throws(()=>orderEmail({...o,shopEmail:'x\r\nBcc:bad@test.test'},'invoice'));assert.throws(()=>orderEmail(o,'anything'));});
function transport(status='queued'){const calls=[];return {calls,rpc:async(name,args)=>{calls.push([name,args]);if(name==='ce_email_prepare')return {status,snapshot:o,provider_id:'existing'};if(name==='ce_email_claim')return {payload:args.content};}};}
test('no key fails closed without sending',async()=>{let called=false;const r=await sendOrderEmail({rpc:async()=>{called=true},orderId:o.id,kind:'invoice'});assert.equal(r.status,'not_configured');assert(!called);});
test('accepted mail never resends',async()=>{const t=transport('accepted');const r=await sendOrderEmail({...t,apiKey:'test',orderId:o.id,kind:'invoice',fetcher:()=>{throw Error('must not send')}});assert.equal(r.status,'accepted');assert.equal(t.calls.length,1);});
test('provider success is accepted and has stable idempotency key',async()=>{const t=transport();const r=await sendOrderEmail({...t,apiKey:'test',orderId:o.id,kind:'invoice',fetcher:async(url,opts)=>{assert.equal(opts.headers['Idempotency-Key'],'ce-invoice-order1');assert.deepEqual(JSON.parse(opts.body).to,[o.shopEmail]);return {ok:true,json:async()=>({id:'provider-1'})};}});assert.equal(r.status,'accepted');assert.equal(t.calls.at(-1)[1].outcome,'accepted');});
test('timeouts and server errors stay unknown, explicit rejection can retry',async()=>{for(const code of [null,500,403]){const t=transport();const r=await sendOrderEmail({...t,apiKey:'test',orderId:o.id,kind:'confirmation',fetcher:async()=>{if(!code)throw Error('timeout');return {ok:false,status:code,json:async()=>({message:'secret'})};}});assert.equal(r.status,code===403?'failed':'unknown');assert(!r.issue.includes('secret'));}});
