import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {invoiceBalance,checkoutPayload,paymentElementConfig,elementPaymentPayload,reservationPaymentPayload,safeCheckoutUrl,verifyWhopWebhook,applyWhopPayment,whopRequest,whopPaymentRequest} from '../supabase/functions/_shared/whop.mjs';
const o=()=>({id:'o1',invoiceNumber:'INV1',shopEmail:'shop@example.test',totalCents:10000,amountPaidCents:2000,paymentStatus:'PARTIAL',paymentCheckout:{id:'ch_123',reference:'ref1',amountCents:8000,beforePaidCents:2000,status:'ready'}});
const source=()=>({orders:[o()],accounts:[],crm:{activities:[]}});const payment=()=>({id:'pay_123',status:'paid',currency:'usd',account_id:'biz_123',checkout_configuration_id:'ch_123',metadata:{ce_order_id:'o1',ce_reference:'ref1'},total:{amount:'80.00',currency:'usd'}});
test('checkout uses recorded invoice balance and fixed return origin',()=>{const p=checkoutPayload(o(),'biz_123','ref1');assert.equal(p.plan.initial_price,80);assert.equal(p.plan.plan_type,'one_time');assert.match(p.redirect_url,/^https:\/\/www.converterexpress.net/);assert.throws(()=>invoiceBalance({...o(),paymentStatus:'PAID'}));assert.throws(()=>invoiceBalance({...o(),amountPaidCents:undefined}));assert.throws(()=>safeCheckoutUrl('https://evil.example'));});
test('webhook verifies Whop literal signing secret and rejects tampering/stale payloads',async()=>{const now=Date.now(),ts=String(Math.floor(now/1000)),raw=JSON.stringify({type:'payment.succeeded'}),id='evt_1',secret='ws_test_only';const signature=createHmac('sha256',secret).update(id+'.'+ts+'.'+raw).digest('base64'),headers=new Headers({'webhook-id':id,'webhook-timestamp':ts,'webhook-signature':'v1,'+signature});assert.equal((await verifyWhopWebhook(raw,headers,secret,now)).type,'payment.succeeded');await assert.rejects(verifyWhopWebhook(raw+' ',headers,secret,now));await assert.rejects(verifyWhopWebhook(raw,headers,secret,now+301000));});
test('verified exact payment closes invoice once and stores method',()=>{const a=applyWhopPayment(source(),payment(),'biz_123');assert.equal(a.data.orders[0].paymentStatus,'PAID');assert.equal(a.data.orders[0].paymentMethod,'Whop');assert(a.data.orders[0].invoiceClosedAt);const b=applyWhopPayment(a.data,payment(),'biz_123');assert.equal(b.duplicate,true);assert.equal(b.data.orders[0].whopReceipts.length,1);});
test('wrong merchant, pending, currency, checkout, amount and refunded payments cannot credit invoices',()=>{for(const change of [{account_id:'biz_other'},{status:'pending'},{currency:'eur'},{checkout_configuration_id:'ch_other'},{total:{amount:'0.80',currency:'usd'}},{refunded_at:'today'}])assert.throws(()=>applyWhopPayment(source(),{...payment(),...change},'biz_123'));});
test('canceled or changed invoice retains incoming receipt for review and never closes automatically',()=>{const s=source();s.orders[0].cancelled=true;const a=applyWhopPayment(s,payment(),'biz_123');assert.equal(a.review,true);assert.equal(a.data.orders[0].paymentStatus,'PARTIAL');assert.equal(a.data.orders[0].whopReceipts.length,1);});

test('element configuration and confirmation payload use the exact server-owned invoice balance',()=>{const config=paymentElementConfig(o(),'biz_123');assert.deepEqual(config,{accountId:'biz_123',currency:'usd',amount:8000});const payload=elementPaymentPayload(o(),'biz_123','reference-123','ctok_ABC123','shop@example.test');assert.equal(payload.account_id,'biz_123');assert.equal(payload.confirmation_token,'ctok_ABC123');assert.equal(payload.email,'shop@example.test');assert.equal(payload.plan.initial_price,80);assert.equal(payload.plan.plan_type,'one_time');assert.deepEqual(payload.metadata,{ce_order_id:'o1',ce_reference:'reference-123'});assert.throws(()=>elementPaymentPayload(o(),'biz_123','reference-123','not-a-token','shop@example.test'));});
test('reservation payment payload routes the webhook to the reservation',()=>{const payload=reservationPaymentPayload({id:'r1',amount_cents:12500,payment_reference:'reference-123'},'biz_123','ctok_ABC123','shop@example.test');assert.equal(payload.plan.initial_price,125);assert.deepEqual(payload.metadata,{ce_reservation_id:'r1',ce_reference:'reference-123'});assert.throws(()=>reservationPaymentPayload({id:'r1',amount_cents:0,payment_reference:'reference-123'},'biz_123','ctok_ABC123','shop@example.test'));});

test('direct element payment matches its reserved payment id instead of a checkout configuration',()=>{const s=source();s.orders[0].paymentCheckout={...s.orders[0].paymentCheckout,id:'pay_123',mode:'element',status:'processing'};const p={...payment(),checkout_configuration_id:null};const result=applyWhopPayment(s,p,'biz_123');assert.equal(result.data.orders[0].paymentStatus,'PAID');assert.equal(result.data.orders[0].paymentCheckout.status,'paid');});

test('REST adapter pins the matching API version and checkout idempotency key',async()=>{await whopRequest('checkout_configurations','test-only',checkoutPayload(o(),'biz_123','ref1'),async(url,options)=>{assert.equal(options.headers['Api-Version-Date'],'2026-09-29');assert.equal(options.headers['Idempotency-Key'],'ref1');const plan=JSON.parse(options.body).plan;assert.equal(plan.stock,1);assert.equal(plan.unlimited_stock,false);assert.equal(plan.force_create_new_plan,true);return {ok:true,json:async()=>({})};});});
test('element payment adapter uses the Payment Elements API version and reservation idempotency key',async()=>{const payload=elementPaymentPayload(o(),'biz_123','reference-123','ctok_ABC123','shop@example.test');await whopPaymentRequest('payments','test-only',payload,async(url,options)=>{assert.equal(url,'https://api.whop.com/api/v1/payments');assert.equal(options.headers['Api-Version-Date'],'2026-10-08');assert.equal(options.headers['Idempotency-Key'],'reference-123');return {ok:true,json:async()=>({id:'pay_123'})};});});
